"""Source for src/data/cases/breast.json. Edit here, then run:
    python3 tools/cases/breast_cases.py
Same step format as headneck_cases.py."""
import json, os

TRIAL = "Landmark trial"

def mcq(label, prompt, choices, correct, explanation, **extra):
    return {"label": label, **extra, "prompt": prompt, "choices": choices, "correctIndex": correct, "explanation": explanation}

def fill(label, prompt, answer, explanation="", **extra):
    return {"label": label, **extra, "prompt": prompt, "answer": answer, "explanation": explanation}

CASES = [
  {
    "id": "br-case-1", "level": "Foundational",
    "title": "Case 1: A Lump in the Shower",
    "oneLiner": "A 27-year-old woman felt a smooth, rubbery lump in her left breast while showering. It moves easily under her fingers and doesn't hurt. She has no family history of breast or ovarian cancer.",
    "steps": [
      mcq("First test",
        "What is the best first imaging test?",
        ["Screening mammogram", "Targeted breast ultrasound", "Breast MRI", "PET/CT"],
        1,
        "Young women have dense breast tissue that hides masses on a mammogram, so a palpable lump in a woman under 30 gets an ultrasound first. Ultrasound also answers the first question: solid or cyst?"),
      mcq("Ultrasound",
        "Which feature, had it been present, would have made this mass suspicious for cancer?",
        ["Oval shape", "Circumscribed margins", "Taller than wide, with posterior acoustic shadowing", "Wider than tall"],
        2,
        "Suspicious masses are hypoechoic, irregular or spiculated, taller than wide, and cast a posterior shadow. Reassuring masses are oval, circumscribed, wider than tall, and may show posterior enhancement.",
        context="<p><strong>Ultrasound:</strong> a 1.8 cm oval, circumscribed, evenly hypoechoic solid mass, <strong>wider than tall</strong>, with no posterior shadowing.</p>",
        image="images/breast/br-c-fibroadenoma.jpg",
        caption="Breast ultrasound of a solid mass. Nevit Dilmen, Wikimedia Commons, CC BY-SA 3.0."),
      mcq("Biopsy method",
        "Because the lump is new and palpable, it is biopsied. Why use a core needle biopsy rather than FNA for a breast mass?",
        ["FNA is more painful",
         "FNA gives loose cells, not tissue architecture, so it can't tell DCIS from invasive cancer",
         "Core biopsy is cheaper",
         "FNA can't be guided by ultrasound"],
        1,
        "Core biopsy keeps the tissue architecture, so the pathologist can see invasion and run ER, PR, and HER2. A clip is placed so the spot can be found later."),
      mcq("Diagnosis",
        "The core biopsy shows a fibroadenoma with no atypia. What is the right plan?",
        ["Lumpectomy and whole-breast RT",
         "Reassurance, with observation or elective removal if it grows or bothers her",
         "Mastectomy",
         "Tamoxifen for 5 years"],
        1,
        "A fibroadenoma is a benign tumor and the most common breast mass in young women. There is no cancer to stage and no role for radiation."),
      mcq("If it had been cancer",
        "Imagine the biopsy had shown cancer instead. Which referral would her age alone call for?",
        ["Genetic counseling and testing", "Cardiology", "A bone scan", "Dermatology"],
        0,
        "Young age is an indication for genetic counseling. A result like BRCA or TP53 changes surgery and radiation choices: partial breast RT is generally avoided in BRCA carriers, and Li-Fraumeni patients avoid radiation when possible."),
    ],
  },
  {
    "id": "br-case-2", "level": "Foundational",
    "title": "Case 2: The Callback",
    "oneLiner": "A 66-year-old woman with no symptoms is called back after her routine screening mammogram.",
    "steps": [
      mcq("Mammogram",
        "The magnified views show fine, linear, branching (casting) calcifications over a 2.5 cm segment, BI-RADS 4C. What do calcifications like these most suggest?",
        ["Benign fat necrosis", "High-grade (comedo) DCIS", "A fibroadenoma", "An intramammary lymph node"],
        1,
        "Linear and casting calcifications suggest high-grade (comedo) DCIS; fine granular ones suggest lower-grade DCIS. DCIS shows up as calcifications alone in 50-75% of cases, and its true extent is usually larger than the calcifications.",
        image="images/breast/br-g-calcs.jpg",
        caption="Magnified craniocaudal mammogram view of the area of concern."),
      mcq("Biopsy",
        "There is no mass on ultrasound, only the calcifications. Which biopsy is right?",
        ["Ultrasound-guided core biopsy", "Stereotactic (mammogram-guided) core biopsy", "Punch biopsy of the skin", "FNA"],
        1,
        "Calcifications that are only seen on mammogram are sampled with a stereotactic core biopsy. Ultrasound guidance is for masses seen on ultrasound, and MRI guidance is for findings seen only on MRI."),
      fill("Pathology",
        "What is her stage?",
        "Tis N0 M0, Stage 0",
        "DCIS is Tis. For DCIS, a margin of at least 2 mm is the goal, and she has it. Lobular carcinoma in situ is no longer staged as Tis.",
        context="<p><strong>Stereotactic core biopsy:</strong> ductal carcinoma in situ, high nuclear grade with comedo necrosis, ER positive. <strong>Lumpectomy:</strong> 2.2 cm of DCIS, no invasion, margins negative (closest 3 mm).</p>"),
      mcq("Trial",
        "She asks what radiation would buy her. Which trials showed that adding RT after lumpectomy for DCIS cuts in-breast recurrence about in half, without changing survival?",
        ["NSABP B-17 and EORTC 10853", "NSABP B-06 and the Milan trial", "ACOSOG Z0011", "MA.20 and EORTC 22922"],
        0,
        "NSABP B-17 and EORTC 10853 established RT after lumpectomy for DCIS. About half of in-breast recurrences after DCIS are invasive, which is why preventing them matters even without a survival difference. NSABP B-06 and Milan are the invasive-cancer lumpectomy trials.",
        tag=TRIAL),
      mcq("Plan",
        "What do you recommend?",
        ["No further treatment, since she is low risk",
         "Whole-breast RT (for example 40 Gy in 15 fractions), and consider endocrine therapy because it is ER positive",
         "Mastectomy plus RT",
         "Whole-breast RT plus regional nodal irradiation"],
        1,
        "She isn't low risk: omission (RTOG 9804) is for small, low or intermediate grade DCIS with widely clear margins, and hers is high grade with comedo necrosis. Nodes are not treated for DCIS. ER-positive DCIS can get endocrine therapy for risk reduction."),
      fill("Side effects",
        "What side effects of whole-breast RT should you counsel her about?",
        "During and just after: fatigue, skin redness and irritation (sometimes peeling in the fold under the breast), breast swelling, and tenderness. Later: breast firmness or shrinkage, skin color changes, and rare rib fracture, lung inflammation (pneumonitis), heart effects, or second cancers.",
        "Hypofractionated courses (40 Gy in 15 or 26 Gy in 5) matched longer courses for side effects in START B and FAST-Forward."),
    ],
  },
  {
    "id": "br-case-3", "level": "Intermediate",
    "title": "Case 3: The Grandmother's Question",
    "oneLiner": "A 73-year-old woman with high blood pressure and arthritis has a new 1.3 cm mass in her left breast found on screening. She looks after her grandchildren and wants the least treatment that is still safe.",
    "steps": [
      mcq("Mammogram",
        "The mass is irregular and spiculated. What BI-RADS category fits, and what is next?",
        ["BI-RADS 2: return to routine screening",
         "BI-RADS 3: repeat mammogram in 6 months",
         "BI-RADS 4-5: core needle biopsy",
         "BI-RADS 6: start treatment"],
        2,
        "A spiculated mass is one of the three classic suspicious findings, with pleomorphic or linear calcifications and architectural distortion. BI-RADS 4 or 5 means biopsy; BI-RADS 6 is for cancer that is already biopsy-proven.",
        image="images/breast/br-g-mammo-cc.jpg",
        caption="Craniocaudal mammogram: an irregular, spiculated, high-density mass in the left breast. Razdan S et al., Cureus 2025 (PMC12791182), CC BY 4.0."),
      fill("Pathology",
        "What is her anatomic stage, and which molecular subtype does this look like?",
        "pT1c N0 M0, Stage IA. Luminal A-like (hormone receptor positive, HER2 negative, low grade).",
        "1.3 cm is T1c (over 1 cm and up to 2 cm). HER2 1+ is negative. Luminal A is the most common subtype, has the best prognosis, and responds to endocrine therapy.",
        context="<p><strong>Ultrasound-guided core biopsy:</strong> invasive ductal carcinoma, grade 1, <strong>ER 95%, PR 80%, HER2 1+</strong>. Axilla normal on ultrasound. <strong>Lumpectomy and sentinel node biopsy:</strong> 1.3 cm, margins negative, 0 of 2 sentinel nodes positive.</p>"),
      mcq("Systemic",
        "Which systemic therapy is the backbone of her treatment?",
        ["Trastuzumab", "An aromatase inhibitor for 5-10 years", "Pembrolizumab", "Chemotherapy, then tamoxifen"],
        1,
        "Hormone receptor positive, HER2 negative disease is treated with endocrine therapy for 5-10 years: an aromatase inhibitor after menopause, tamoxifen before. Chemo for HR+ disease is decided by a genomic score, and a small grade 1 tumor like hers is unlikely to need it."),
      mcq("Trial",
        "She asks whether she can skip radiation. Which trials support omitting RT for older patients with small, ER-positive, node-negative cancers who take endocrine therapy?",
        ["CALGB 9343 and PRIME II", "START B and FAST-Forward", "NSABP B-17 and EORTC 10853", "KEYNOTE-522"],
        0,
        "In CALGB 9343 and PRIME II, skipping RT raised local recurrence slightly but did not change survival. START B and FAST-Forward are the hypofractionation trials.",
        tag=TRIAL),
      mcq("Trade-off",
        "If she skips RT, which statement is true?",
        ["Her survival will be lower",
         "Her risk of a breast recurrence rises slightly, survival is the same, and the plan depends on her actually taking endocrine therapy",
         "She will need a mastectomy",
         "Her lymph nodes must be irradiated instead"],
        1,
        "The omission trials enrolled women taking endocrine therapy. If she doesn't plan to take it, the case for skipping RT gets much weaker."),
      fill("If she wants RT",
        "If she chooses radiation, what is the shortest evidence-based whole-breast regimen, and what is one alternative?",
        "26 Gy in 5 daily fractions over 1 week (FAST-Forward). Alternative: partial breast RT (for example 30 Gy in 5 fractions), since she meets low-risk criteria.",
        "40 Gy in 15 fractions is also standard. She doesn't need a boost: she is over 50, the tumor is low grade, and the margins are negative."),
    ],
  },
  {
    "id": "br-case-4", "level": "Intermediate",
    "title": "Case 4: The Left-Sided Plan",
    "oneLiner": "A 44-year-old premenopausal woman had a lumpectomy and sentinel node biopsy for a 2.4 cm grade 3, ER-positive, HER2-negative invasive ductal carcinoma of the left breast. Margins are negative and 0 of 3 sentinel nodes are involved. Her Oncotype DX score is high.",
    "steps": [
      fill("Stage",
        "What is her anatomic pathologic stage?",
        "pT2 N0 M0, Stage IIA",
        "2.4 cm is T2 (over 2 cm and up to 5 cm). T2 N0 is stage IIA."),
      mcq("Sequencing",
        "Because of the high Oncotype score, she will get adjuvant chemotherapy. How is it sequenced with radiation?",
        ["Chemo and RT at the same time",
         "Chemo first, then RT, then years of endocrine therapy",
         "RT first, then chemo a year later",
         "Endocrine therapy first, then chemo, then RT"],
        1,
        "Chemo is never given at the same time as breast RT. Endocrine therapy and anti-HER2 drugs, by contrast, can run during RT."),
      mcq("Fields",
        "What radiation does she need?",
        ["Whole breast plus the regional nodes",
         "Whole breast plus a tumor bed boost, no nodal fields",
         "Partial breast RT only",
         "No radiation"],
        1,
        "She is node-negative, so no nodal fields. Age 50 or younger and high grade are both boost indications. She is too young for partial breast RT or omission."),
      mcq("The heart",
        "On her simulation CT the heart sits right against the left chest wall. What is the best way to lower heart dose?",
        ["Widen the tangent fields", "Deep inspiration breath hold (DIBH)", "Add the internal mammary nodes", "Skip the boost"],
        1,
        "Major cardiac events rise about 7% per Gy of mean heart dose (Darby). A deep breath fills the lungs and pushes the heart down and away from the tangents. Adding the internal mammary nodes would make heart sparing harder, not easier.",
        image="images/breast/br-g-dibh.jpg",
        caption="Planning CT in free breathing (left) vs deep inspiration breath hold (right): the heart moves from 3.1 to 4.1 cm away from the chest wall. M A et al., Cureus 2025 (PMC12579725), CC BY 4.0."),
      mcq("Structures",
        "On this beam's-eye view, which coronary artery is most at risk because it runs along the front of the heart, right under the tangents?",
        ["Right coronary artery", "Left anterior descending (LAD)", "Circumflex artery", "Posterior descending artery"],
        1,
        "The LAD runs down the anterior heart, closest to the medial tangent, which is why it gets contoured on every left-sided plan.",
        image="images/breast/br-g-drr.jpg",
        caption="Beam's-eye view of a medial tangent with the breast target, heart, left ventricle, LAD, and lung outlined. Park S et al., Radiat Oncol 2021 (PMC8056628), CC BY 4.0."),
      fill("Dose",
        "Give a dose and fractionation for her whole breast and boost.",
        "Whole breast: 40 Gy in 15 fractions (or 26 Gy in 5). Tumor bed boost: 10 Gy in 4 fractions or 16 Gy in 8 (or a simultaneous boost).",
        "START B and FAST-Forward made hypofractionation the standard: shorter courses matched longer ones for control and side effects."),
      fill("8 months later",
        "Eight months after RT she asks what she should still keep an eye on. Which late effects of left breast RT do you mention?",
        "Breast firmness or shrinkage, skin color change and small visible blood vessels (telangiectasias), occasional chest wall pain or rare rib fracture, rare radiation pneumonitis (dry cough, low fever, shortness of breath, usually in the first months after RT), and long-term heart risk, which is why her heart dose was kept low.",
        "Arm swelling is uncommon here because she had only a sentinel node biopsy and no nodal RT."),
    ],
  },
  {
    "id": "br-case-5", "level": "Intermediate",
    "title": "Case 5: Two of Three",
    "oneLiner": "A 58-year-old postmenopausal woman has a 2.8 cm ER-positive, HER2-negative invasive ductal carcinoma in the upper outer quadrant of her right breast. Her armpit feels normal and looks normal on ultrasound.",
    "steps": [
      mcq("Axilla",
        "How should her clinically negative axilla be staged?",
        ["Axillary lymph node dissection", "Sentinel lymph node biopsy", "PET/CT", "No axillary surgery at all"],
        1,
        "Sentinel node biopsy is standard for a clinically negative axilla. Full dissection is kept for bulky or matted nodes, inflammatory cancer, and nodes that stay positive after neoadjuvant chemo, because it causes lymphedema in about 20-25% of patients. Omitting SLNB is only considered in select patients 70 or older."),
      fill("Pathology",
        "What is her pathologic stage?",
        "pT2 N1a M0, Stage IIB",
        "1-3 positive axillary nodes, at least one over 2 mm, is pN1a. T2 N1 is stage IIB.",
        context="<p><strong>Lumpectomy and sentinel node biopsy:</strong> 2.8 cm invasive ductal carcinoma, grade 2, margins negative. <strong>2 of 3 sentinel nodes positive</strong> (largest deposit 6 mm), no extranodal extension.</p>",
        image="images/breast/br-g-lsg.jpg",
        caption="Sentinel node mapping (lymphoscintigraphy and SPECT/CT) in another patient: tracer injected in the breast drains to the first nodes in the axilla. Israel O et al., Eur J Nucl Med Mol Imaging 2019 (PMC6667427), CC BY 4.0."),
      mcq("Trial",
        "The surgeon asks whether she needs to go back for a full axillary dissection. Which trial says no for exactly this situation (cT1-2, cN0, 1-2 positive sentinel nodes, lumpectomy plus whole-breast RT)?",
        ["ACOSOG Z0011", "AMAROS", "NSABP B-06", "MA.20"],
        0,
        "In Z0011, skipping the dissection did not change survival for these patients. AMAROS asked a related question (axillary RT instead of dissection), and MA.20 asked about regional nodal RT.",
        tag=TRIAL),
      mcq("Anatomy",
        "In this drawing of the right axilla the nodes are colored by level. Which muscle, crossing the middle of the nodes, defines levels I, II, and III?",
        ["Pectoralis major", "Pectoralis minor", "Latissimus dorsi", "Serratus anterior"],
        1,
        "Lateral to the pectoralis minor is level I, behind it is level II, and medial to it is level III (infraclavicular). Standard tangents cover much of level I, and high tangents more of levels I-II, which is part of why Z0011 worked.",
        image="images/breast/br-axillary-levels.jpg",
        caption="Drawing of the right axilla with the nodes colored by level. Lu Q et al., PLoS One 2013 (PMC3702586), CC BY 4.0."),
      mcq("Radiation",
        "With 2 positive sentinel nodes and no dissection, which radiation plan fits?",
        ["No radiation",
         "Whole-breast RT (often with high tangents), adding regional nodal RT based on her other risk features",
         "Partial breast RT",
         "RT to the dissected axilla only"],
        1,
        "Z0011-type patients get whole-breast RT, often with high tangents. Regional nodal RT is decided by other risk features; MA.20 and EORTC 22922 showed that adding it in node-positive disease improves disease-free survival."),
      mcq("What if",
        "Change one detail: she had a mastectomy instead, with the same 2 positive sentinel nodes. Which trial supports axillary RT instead of a dissection?",
        ["AMAROS", "Z0011", "CALGB 9343", "FAST-Forward"],
        0,
        "Z0011 only applies to lumpectomy plus whole-breast RT. AMAROS showed that axillary RT gives the same axillary control as dissection with about half the lymphedema."),
    ],
  },
  {
    "id": "br-case-6", "level": "Advanced",
    "title": "Case 6: After the Mastectomy",
    "oneLiner": "A 49-year-old woman had a right mastectomy with axillary dissection for a palpable 4.5 cm mass and has finished adjuvant chemotherapy. She is planning delayed reconstruction.",
    "steps": [
      fill("Pathology",
        "What is her pathologic stage?",
        "pT2 N2a M0, Stage IIIA",
        "4-9 positive axillary nodes is pN2a. Any T0-2 with N2 is stage IIIA.",
        context="<p><strong>Pathology:</strong> 4.5 cm invasive ductal carcinoma, grade 3, ER and PR positive, HER2 negative, lymphovascular invasion present, margins negative. <strong>4 of 12</strong> axillary nodes positive (levels I-II dissected), no extranodal extension.</p>"),
      mcq("PMRT",
        "Does she need post-mastectomy radiation (PMRT)?",
        ["No, the margins are negative",
         "Yes: 4 or more positive nodes is a clear PMRT indication",
         "Only if the tumor had been over 5 cm",
         "Only if she skips reconstruction"],
        1,
        "PMRT is indicated for T3-T4 tumors, 4 or more positive nodes, or a positive margin, and strongly considered for 1-3 nodes."),
      mcq("Nodal levels",
        "Which regions belong in her target?",
        ["Chest wall only",
         "Chest wall plus level III (infraclavicular), supraclavicular, and internal mammary nodes",
         "Chest wall plus full re-treatment of the dissected levels I-II, and nothing else",
         "Supraclavicular nodes only"],
        1,
        "PMRT treats the chest wall and regional nodes. A dissected axilla (levels I-II) usually isn't retreated, because RT on top of a dissection sharply raises lymphedema risk. The internal mammary nodes sit beside the sternum in intercostal spaces 1-3.",
        image="images/breast/br-nodal-basins.jpg",
        caption="Front view of the chest showing lymphatic drainage of the right breast (on your left): toward the axilla, up to the clavicle, and medially along the sternum."),
      mcq("Trial",
        "Which trials showed that adding regional nodal RT for node-positive patients improves disease-free survival and reduces distant metastases?",
        ["MA.20 and EORTC 22922", "START B and FAST-Forward", "CALGB 9343 and PRIME II", "NSABP B-17"],
        0,
        "MA.20 and EORTC 22922 are the regional nodal irradiation trials, and they are why node-positive patients get the nodes added to the target.",
        tag=TRIAL),
      fill("Dose",
        "What is a typical dose to the chest wall and nodes, and when is bolus used?",
        "50 Gy in 25 fractions (hypofractionation is increasingly used). Bolus is added when the skin is at risk.",
        "Radiation raises the risk of implant complications, so delayed reconstruction is planned with the radiation team."),
      mcq("Toxicity",
        "Which risks are specifically raised by treating the supraclavicular and level III region after an axillary dissection?",
        ["Brachial plexopathy and arm lymphedema", "Cystitis", "Hearing loss", "Hypothyroidism alone"],
        0,
        "The brachial plexus runs just behind the supraclavicular and level III targets, and dissection plus nodal RT stacks lymphedema risk. Pneumonitis is also more likely when the nodes are treated."),
      mcq("8 months later",
        "Eight months after PMRT her right ring feels tight and her sleeve is snug by evening. Her arm looks like this. What is the most likely cause and the first step?",
        ["Axillary recurrence; start chemotherapy",
         "Lymphedema from dissection plus nodal RT; refer for compression and decongestive therapy, and rule out a clot or recurrence if it is sudden or painful",
         "Radiation pneumonitis",
         "Normal swelling that needs no follow-up"],
        1,
        "Lymphedema is the classic late effect of axillary dissection plus nodal RT. Early referral to a lymphedema therapist works best. A sudden, painful, or rapidly worsening swelling still deserves a workup for a clot or recurrence.",
        image="images/breast/br-c-lymphedema.jpg",
        caption="Secondary lymphedema of the right arm in another patient. Dionyssiou D et al., JPRAS Open 2025 (PMC11751497), CC BY 4.0."),
    ],
  },
  {
    "id": "br-case-7", "level": "Advanced",
    "title": "Case 7: The Rash That Wasn't",
    "oneLiner": "A 51-year-old woman has had 5 weeks of a red, warm, swollen right breast. She was treated for mastitis with two courses of antibiotics, but the redness has spread to cover more than half of the breast.",
    "steps": [
      mcq("Exam",
        "What is the leading diagnosis, and how is it confirmed?",
        ["Resistant mastitis: switch antibiotics",
         "Inflammatory breast cancer: core biopsy of the breast plus a punch biopsy of the skin",
         "Breast abscess: incision and drainage",
         "Contact dermatitis: topical steroids"],
        1,
        "Rapid-onset redness and edema covering at least a third of the breast that doesn't respond to antibiotics is inflammatory breast cancer until proven otherwise. It is a clinical diagnosis confirmed with a biopsy, often with no discrete mass.",
        context="<p>The skin over most of the right breast is red and thickened with an orange-peel texture. No discrete mass is felt. A firm, matted cluster of right axillary nodes is palpable.</p>",
        image="images/breast/br-g-peau.jpg",
        caption="The right breast on exam. Levine PH et al., Cancers 2010 (PMC3827596), CC BY 3.0."),
      fill("Stage",
        "What are her clinical T and N, and what staging comes next?",
        "cT4d cN2a, at least Stage IIIB. She needs full staging: PET/CT (or CT chest, abdomen, and pelvis plus a bone scan), and an echocardiogram before anti-HER2 therapy.",
        "Inflammatory cancer is T4d, not just T4b skin involvement. Matted or fixed level I-II nodes are cN2a. Stage III disease always gets systemic staging imaging.",
        context="<p><strong>Core biopsy:</strong> invasive ductal carcinoma, grade 3, ER negative, PR negative, <strong>HER2 3+</strong>. <strong>Skin punch biopsy:</strong> tumor in the dermal lymphatics. The matted axillary nodes are biopsy-proven.</p>"),
      fill("PET/CT",
        "Does this change her N stage?",
        "Yes. Internal mammary plus axillary nodes is cN3b, so she is now Stage IIIC. It is still regional disease, and the goal is still cure.",
        "Internal mammary nodes alone would be cN2b; together with axillary nodes they are cN3b. Supraclavicular nodes are cN3c. None of these is M1.",
        context="<p><strong>PET/CT:</strong> intense uptake in the right breast, the matted right axillary nodes, and an ipsilateral <strong>internal mammary</strong> node. No distant disease.</p>",
        image="images/breast/br-g-pet-mip.jpg",
        caption="PET maximum-intensity projection: right breast primary (arrow) with axillary and internal mammary nodal disease. Nyamieri D et al., Front Nucl Med 2025 (PMC12868128), CC BY 4.0."),
      mcq("Sequence",
        "What is the correct order of treatment?",
        ["Lumpectomy and sentinel node biopsy, then RT",
         "Neoadjuvant chemo with trastuzumab and pertuzumab, then modified radical mastectomy with level I-II dissection, then PMRT",
         "Mastectomy now, chemo later, and no RT if there is a complete response",
         "RT first, then surgery, then chemo"],
        1,
        "Inflammatory cancer always gets neoadjuvant systemic therapy, then a modified radical mastectomy (no lumpectomy, no sentinel node biopsy, delayed reconstruction), then PMRT whatever the response."),
      fill("Target",
        "What does her PMRT cover, and what is done for the skin?",
        "The chest wall with bolus, plus the infraclavicular (level III), supraclavicular, and internal mammary nodes (with a boost to the involved internal mammary node), and any undissected axilla at risk.",
        "In inflammatory cancer the skin is part of the target, so bolus is used to bring full dose to the surface."),
      mcq("Trial",
        "At surgery she still has residual invasive cancer, so her anti-HER2 therapy is switched to T-DM1. Which trial supports this?",
        ["KATHERINE", "KEYNOTE-522", "TAILORx", "RxPONDER"],
        0,
        "KATHERINE: HER2-positive patients with residual disease after neoadjuvant therapy do better with T-DM1. KEYNOTE-522 is the pembrolizumab trial for triple-negative disease; TAILORx and RxPONDER are the Oncotype DX trials.",
        tag=TRIAL),
      mcq("Counseling",
        "Which acute side effect will likely be worse than in a typical breast patient, because of the bolus and nodal fields?",
        ["Skin reaction, including peeling in the armpit and the fold under the breast", "Hearing loss", "Diarrhea", "Scalp hair loss"],
        0,
        "Bolus deliberately brings dose to the skin, so a brisk skin reaction (moist desquamation in folds) is expected and managed with skin care during and after treatment."),
    ],
  },
  {
    "id": "br-case-8", "level": "Advanced",
    "title": "Case 8: Nothing Left at Surgery",
    "oneLiner": "A 36-year-old woman whose mother had ovarian cancer at 45 found a 3 cm lump in her left breast. She also has a firm 1.5 cm node just above her left collarbone.",
    "steps": [
      mcq("The node",
        "A biopsy-proven node above the clavicle in breast cancer is staged as:",
        ["M1, so she is incurable", "cN3c, Stage IIIC, still treated for cure", "cN1", "cN2b"],
        1,
        "Supraclavicular nodes are regional (cN3c), not distant. Any N3 is stage IIIC, whatever the size of the primary. A contralateral axillary or supraclavicular node, by contrast, would be M1."),
      mcq("Biology",
        "Which part of her story should prompt genetic testing, and which gene is most likely?",
        ["A triple-negative cancer at 36 with a mother who had ovarian cancer: BRCA1",
         "Her tumor size: TP53",
         "The grade: PTEN",
         "None; testing isn't needed"],
        0,
        "Young age, triple-negative disease, and a family history of ovarian cancer all point to BRCA1, which is strongly linked to triple-negative cancer.",
        context="<p><strong>Core biopsy:</strong> invasive ductal carcinoma, grade 3, <strong>ER 0%, PR 0%, HER2 0</strong>. The supraclavicular node is positive for carcinoma. <strong>PET/CT:</strong> left breast primary, left axillary nodes, and the left supraclavicular node; no distant disease.</p>"),
      mcq("Trial",
        "She starts neoadjuvant chemotherapy plus pembrolizumab. Which trial established this for stage II-III triple-negative breast cancer?",
        ["KEYNOTE-522", "KATHERINE", "MA.20", "TAILORx"],
        0,
        "KEYNOTE-522 added pembrolizumab to neoadjuvant chemo (and continued it after surgery) for stage II-III triple-negative disease. KATHERINE is the T-DM1 trial for residual HER2-positive disease.",
        tag=TRIAL),
      mcq("Response",
        "Her pathology shows ypT0 ypN0, a complete response. Can radiation be skipped since no cancer is left?",
        ["Yes, a complete response means no RT",
         "No: RT follows the worst, pre-chemo stage, so she needs whole-breast RT plus comprehensive nodal RT including the supraclavicular fossa",
         "Only partial breast RT is needed",
         "Only the supraclavicular node needs treatment"],
        1,
        "Radiation decisions after neoadjuvant chemo use both the pre-chemo clinical stage and the yp stage, and N3 disease gets comprehensive RT even after a complete response. Some ypN0 patients may omit nodal RT (NSABP B-51), but that does not apply to supraclavicular disease. This is why the pre-chemo cT and cN must always be written down.",
        context="<p>After chemo-immunotherapy, the breast mass and nodes have nearly disappeared on MRI. <strong>Genetic testing:</strong> a pathogenic <strong>BRCA1</strong> variant. She chooses lumpectomy with targeted axillary surgery. <strong>Pathology: ypT0 ypN0.</strong></p>",
        image="images/breast/br-g-mri-nact.jpg",
        caption="Example of response on contrast-enhanced breast MRI before (left) and after (right) neoadjuvant therapy, from another patient. Matsubayashi RN, Iwakuma N, Jpn J Radiol 2026 (PMC13038685), CC BY 4.0."),
      fill("Nodal levels",
        "List the regions in her radiation target.",
        "The whole left breast (with a tumor bed boost as indicated), level III (infraclavicular), the supraclavicular fossa with a boost to the originally involved node, the internal mammary nodes, and any undissected axilla at risk.",
        "This is comprehensive regional nodal irradiation. The pre-chemo node location decides where the boost goes."),
      mcq("BRCA",
        "How does being a BRCA1 carrier change her options?",
        ["She cannot receive any radiation",
         "Partial breast RT is generally avoided, and many carriers consider risk-reducing mastectomy",
         "She needs a higher radiation dose",
         "Pembrolizumab must be stopped"],
        1,
        "BRCA is not a contraindication to radiation (unlike Li-Fraumeni, where RT is avoided when possible). Had she had residual disease, olaparib (for germline BRCA) or capecitabine would have been added."),
      mcq("Planning",
        "Why is her plan harder to make safe than the node-negative left breast plan in Case 4?",
        ["Treating the left side plus the internal mammary nodes raises heart and lung dose; breath hold and careful planning help",
         "Younger tissue is more resistant to radiation",
         "Supraclavicular fields pass through the bladder",
         "There is no difference"],
        0,
        "Including the internal mammary nodes makes it harder to spare the heart and lung, especially on the left. Breath hold and modern planning techniques are used to keep the mean heart dose low, since cardiac risk rises with every Gy."),
    ],
  },
]

DATA = {
  "category": "Case-Based Practice",
  "intro": "<p>Eight cases that get harder as you go, from a new lump in a young woman to locally advanced cancers treated with all three pillars. Each starts with a one-liner, then gives you more information step by step: imaging and biopsy, the <strong>stage</strong>, the <strong>surgery and systemic therapy</strong>, the <strong>radiation fields and dose</strong>, the <strong>landmark trials</strong>, and the <strong>side effects</strong> to watch for. Some steps are multiple choice, some are fill-in-the-blank. Staging uses the <strong>AJCC 8th edition</strong>, as in the NCCN Breast Cancer Guidelines.</p>",
  "cases": CASES,
}

if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "..", "..", "src", "data", "cases", "breast.json")
    with open(out, "w", encoding="utf8") as f:
        json.dump(DATA, f, ensure_ascii=False, indent=1)
    print("wrote", os.path.normpath(out), len(CASES), "cases")
