"""Source for src/data/cases/cns.json. Run: python3 tools/cases/cns_cases.py"""
from casekit import TRIAL, mcq, fill, write

CASES = [
  {
    "id": "cns-case-7", "level": "Foundational",
    "title": "Case 1: Ringing in One Ear",
    "oneLiner": "A 49-year-old man has a year of gradual hearing loss and ringing in his right ear. His audiogram shows asymmetric sensorineural hearing loss on the right.",
    "steps": [
      mcq("Workup",
        "What is the best test for asymmetric sensorineural hearing loss?",
        ["CT of the sinuses", "MRI of the internal auditory canals with contrast", "Repeat audiogram in 5 years", "Lumbar puncture"],
        1,
        "One-sided sensorineural hearing loss or tinnitus needs a contrast MRI of the internal auditory canals to look for a vestibular schwannoma."),
      mcq("Origin",
        "MRI shows a 1.6 cm enhancing mass widening the right internal auditory canal and extending into the cerebellopontine angle. Which nerve does it arise from?",
        ["Facial nerve (CN VII)", "Vestibular division of CN VIII", "Trigeminal nerve (CN V)", "Glossopharyngeal nerve (CN IX)"],
        1,
        "Vestibular schwannomas (acoustic neuromas) arise from the Schwann cells of the vestibular nerve. The 'ice cream cone' shape comes from the canal portion plus the CPA portion. Hearing loss is from pressure on the neighboring cochlear nerve.",
        image="images/cns/cns-vs.jpg",
        caption="Axial T1 post-contrast MRI: right vestibular schwannoma at the cerebellopontine angle (patient's right on your left). Hellerhoff, Wikimedia Commons, CC BY-SA 3.0."),
      fill("Grade",
        "It grew 3 mm in a year, touches the brainstem, but doesn't compress it. What is the Koos grade?",
        "Koos III",
        "Koos I is in the canal only, II reaches into the CPA, III fills the CPA and touches the brainstem, and IV compresses the brainstem."),
      mcq("Treatment",
        "He wants to avoid surgery and his hearing is still serviceable. What is the best option?",
        ["Observation forever, since it grew", "Stereotactic radiosurgery", "Whole-brain RT", "Craniospinal RT"],
        1,
        "Growing small to medium schwannomas are treated with SRS (about 95% control). Large Koos IV tumors with brainstem compression or hydrocephalus go to surgery."),
      fill("Dose",
        "Give the SRS dose and the key hearing constraint.",
        "12-13 Gy to the tumor margin, keeping the cochlea mean dose at about 4 Gy or less.",
        "Facial nerve injury is rare at these doses. Hearing still tends to decline slowly over years."),
      mcq("Nine months later",
        "Nine months after SRS, MRI shows the tumor is slightly larger with a darker center. He feels fine. What is the most likely explanation?",
        ["Treatment failure; operate now", "Pseudoprogression: temporary swelling that is expected at about 6-18 months after SRS", "Malignant transformation", "A new metastasis"],
        1,
        "Transient enlargement with central loss of enhancement is common after SRS for schwannomas and usually settles. Keep watching with serial MRI before calling it failure."),
    ],
  },
  {
    "id": "cns-case-6", "level": "Foundational",
    "title": "Case 2: Double Vision",
    "oneLiner": "A 55-year-old woman has 6 months of double vision when she looks to the left.",
    "steps": [
      mcq("Diagnosis",
        "MRI shows a 2.5 cm homogeneously enhancing mass in the left cavernous sinus with a dural tail, 4 mm from the optic chiasm. What is the most likely diagnosis?",
        ["Glioblastoma", "Meningioma", "Brain metastasis", "Vestibular schwannoma"],
        1,
        "A homogeneously enhancing, dura-based mass with a dural tail is a meningioma until proven otherwise; many are diagnosed on imaging without a biopsy. Her diplopia is from cranial nerve VI (or III/IV) in the cavernous sinus.",
        image="images/cns/cns-mening.jpg",
        caption="Coronal T1 post-contrast MRI of a different meningioma: a homogeneously enhancing parasagittal mass. James Heilman, MD, Wikimedia Commons, CC BY-SA 4.0."),
      mcq("Surgery?",
        "It grew from 2.0 to 2.5 cm over 18 months and encases the cavernous carotid. Why not simply remove it?",
        ["Meningiomas never respond to surgery",
         "Cavernous sinus tumors encase the carotid and cranial nerves, so resection risks stroke and new nerve deficits and is usually incomplete",
         "It is malignant",
         "Surgery is only for children"],
        1,
        "Accessible, symptomatic meningiomas go to surgery. Inaccessible ones, like this, are treated with radiation."),
      mcq("Options",
        "Which radiation approaches fit a growing cavernous sinus meningioma?",
        ["Whole-brain RT", "SRS 12-14 Gy, or fractionated RT 50.4-54 Gy", "Craniospinal RT", "Observation only"],
        1,
        "Both give about 90-95% control at 5 years. The choice depends on size and distance from the optic apparatus."),
      fill("Choice",
        "With only 4 mm to the chiasm, which do you prefer, and why?",
        "Fractionated RT (for example 50.4-54 Gy in 28-30 fractions) or hypofractionated SRT, because single-fraction SRS may not keep the chiasm at 8-10 Gy or less.",
        "SRS works best when the tumor is a few millimeters away from the optic nerves and chiasm."),
      fill("Side effects",
        "What side effects will you counsel her about?",
        "Fatigue, hair thinning where the beams enter, headache, and rarely injury to nearby nerves (vision loss from optic nerve or chiasm injury) or the pituitary (hormone deficiency over years).",
        "Her double vision may improve, stay the same, or rarely worsen; tumor control means stopping growth, not making it disappear."),
    ],
  },
  {
    "id": "cns-case-4", "level": "Intermediate",
    "title": "Case 3: New Headaches",
    "oneLiner": "A 58-year-old woman with EGFR-negative lung adenocarcinoma, controlled in the chest on chemo-immunotherapy, has two weeks of new headaches.",
    "steps": [
      mcq("Approach",
        "Thin-slice MRI shows three enhancing lesions: 1.5 cm, 1.2 cm, and 2.6 cm, with mild edema. KPS 90. What is the best approach?",
        ["Whole-brain RT", "SRS alone to all three", "Surgery for all three", "Best supportive care"],
        1,
        "SRS alone is standard for limited brain metastases (about 1-4, and up to 10 small ones in selected patients). Surgery is for a large lesion, major mass effect, or when tissue is needed."),
      mcq("Trial",
        "Why not add whole-brain RT to the SRS? Which trial showed more cognitive decline with no survival gain?",
        ["NCCTG N0574", "NRG CC001", "Stupp", "Patchell"],
        0,
        "N0574: adding WBRT improved intracranial control but caused more cognitive decline and did not improve survival.",
        tag=TRIAL),
      fill("Prognosis",
        "Estimate her GPA (2008): age 58, KPS 90, 3 metastases, extracranial disease present.",
        "0.5 (age 50-60) + 1 (KPS 90-100) + 0.5 (2-3 mets) + 0 (extracranial disease) = 2.0",
        "The GPA helps match treatment intensity to prognosis."),
      fill("Doses",
        "What single-fraction doses for the 2.6 cm lesion and the two smaller ones?",
        "18 Gy for the 2.6 cm lesion; 24 Gy for each lesion 2 cm or smaller.",
        "RTOG 90-05: 2 cm or less 24 Gy, 2-3 cm 18 Gy, 3-4 cm 15 Gy. Larger lesions or cavities use 27 Gy in 3 or 30 Gy in 5.",
        image="images/cns/cns-srs-plan.jpg",
        caption="SRS plan for a resection cavity and an intact metastasis: prescription isodose in green, low-dose spill in blue. Lewis J et al., Cureus 2025 (PMC12414254), CC BY 4.0."),
      fill("Follow-up",
        "What follow-up does she need after SRS alone?",
        "MRI every 2-3 months, with SRS for any new lesions.",
        "Radionecrosis (about 5-10%) is the main late risk, higher with larger lesions and with immunotherapy."),
      mcq("What if",
        "Change one detail: the MRI shows 15 metastases and her systemic disease is controlled. Which approach protects memory best if you treat the whole brain?",
        ["WBRT 30 Gy in 10 alone", "Hippocampal-avoidance WBRT plus memantine", "SRS to the largest lesion only", "Craniospinal RT"],
        1,
        "NRG CC001: HA-WBRT plus memantine caused less cognitive failure than WBRT plus memantine.",
        image="images/cns/cns-g-hawbrt.jpg",
        caption="Hippocampal-avoidance whole-brain plan: the two cool spots in the middle are the spared hippocampi. Yang X et al., Eur J Med Res 2023 (PMC9841677), CC BY 4.0."),
    ],
  },
  {
    "id": "cns-case-1", "level": "Intermediate",
    "title": "Case 4: Lost Words",
    "oneLiner": "A 61-year-old man has a new seizure and 3 weeks of trouble finding words and headaches.",
    "steps": [
      mcq("Next step",
        "MRI shows a 4 cm left temporal mass with thick, irregular ring enhancement around a necrotic center and surrounding FLAIR signal. What is the best next step?",
        ["Whole-brain RT", "Maximal safe resection", "SRS", "Start temozolomide now"],
        1,
        "For a presumed high-grade glioma, maximal safe resection gives the diagnosis and molecular markers, relieves mass effect, and improves survival. Near language areas, awake mapping helps. Start dexamethasone and an antiseizure drug.",
        image="images/cns/cns-gbm-t1c.jpg",
        caption="Axial T1 post-contrast MRI: left temporal mass with a thick, irregular enhancing rim around a necrotic center. Armed Forces Institute of Pathology, Wikimedia Commons, public domain."),
      fill("Diagnosis",
        "What is the integrated WHO 2021 diagnosis?",
        "Glioblastoma, IDH-wildtype, WHO grade 4 (MGMT promoter methylated)",
        "IDH-wildtype plus necrosis and/or microvascular proliferation is glioblastoma. MGMT methylation predicts more benefit from temozolomide.",
        context="<p><strong>Post-op MRI (48 h):</strong> gross total resection of the enhancing tumor. <strong>Pathology:</strong> IDH-wildtype glioma with necrosis and microvascular proliferation; <strong>MGMT promoter methylated</strong>. KPS 90.</p>"),
      mcq("Trial",
        "Which trial established 60 Gy in 30 fractions with daily temozolomide, then adjuvant temozolomide?",
        ["Stupp (EORTC/NCIC)", "Perry", "RTOG 9802", "EF-14"],
        0,
        "Stupp improved median survival (14.6 vs 12.1 months) and 5-year survival (about 10% vs 2%). EF-14 added tumor treating fields to adjuvant TMZ.",
        tag=TRIAL),
      fill("Targets",
        "Describe the target volumes.",
        "GTV = resection cavity plus any residual enhancement (± FLAIR); CTV = GTV + about 1.5-2 cm, trimmed at bone, falx, and tentorium; PTV + 3-5 mm. 60 Gy in 30 fractions (or FLAIR to 46 Gy, then a boost to 60 Gy).",
        "Respect the optic chiasm, optic nerves, and brainstem (about 54 Gy)."),
      fill("Counseling",
        "What side effects do you counsel him on?",
        "Fatigue, hair loss in the treated area, scalp irritation, headache or worsening symptoms from swelling (steroids), and temozolomide effects such as nausea, constipation, and low counts (low platelets in particular). Long term: memory and thinking changes.",
        "Patients on concurrent TMZ also get PCP prophylaxis because of lymphopenia."),
      mcq("Eight months later",
        "Eight months after RT, MRI shows a new enhancing area in the treated region. Perfusion imaging is low. He feels well. What is most likely?",
        ["Definite tumor progression", "Treatment effect (radiation necrosis or pseudoprogression)", "A new primary tumor", "Stroke"],
        1,
        "Enhancement inside the high-dose field months after RT can be treatment effect. Low perfusion favors necrosis over tumor, which is usually hyperperfused. Short-interval follow-up, advanced imaging, or tissue sort it out.",
        image="images/cns/cns-post-tx.jpg",
        caption="Treated glioblastoma with a new enhancing lesion (left) proven to be radiation necrosis; the perfusion map (right) shows it is not hyperperfused. Mohamedbaqer Easa A et al., Cureus 2025 (PMC12393895), CC BY 4.0."),
    ],
  },
  {
    "id": "cns-case-2", "level": "Intermediate",
    "title": "Case 5: She Lives Alone",
    "oneLiner": "A 78-year-old woman with a biopsy-proven IDH-wildtype, MGMT-methylated glioblastoma in the left temporal lobe has a KPS of 60. She lives alone and wants to minimize trips to the hospital.",
    "steps": [
      mcq("Approach",
        "Which approach is best supported by evidence for her?",
        ["60 Gy in 30 fractions with TMZ", "40 Gy in 15 fractions with TMZ", "SRS 20 Gy", "No treatment is ever appropriate"],
        1,
        "Shorter courses respect her goals and her frailty while keeping the benefit of TMZ.",
        image="images/cns/cns-gbm-flair.jpg",
        caption="Axial FLAIR MRI of a left temporal glioblastoma with extensive surrounding FLAIR signal and mass effect. Tiwari S, Gyawali I, Cureus 2024 (PMC10944577), CC BY 4.0."),
      mcq("Trial",
        "Which trial showed that adding TMZ to 40 Gy in 15 fractions improved survival in patients 65 and older, especially with MGMT methylation?",
        ["Perry (CCTG CE.6 / EORTC)", "Roa", "Stupp", "QUARTZ"],
        0,
        "Perry established short-course RT plus TMZ for older patients. Roa showed 25 Gy in 5 matched 40 Gy in 15 in older or frail patients.",
        tag=TRIAL),
      mcq("If frailer",
        "What is reasonable if she becomes too frail for chemoRT?",
        ["25 Gy in 5 fractions alone, or TMZ alone (because she is MGMT methylated)", "Craniospinal RT", "Whole-brain RT with hippocampal avoidance", "Prophylactic cranial irradiation"],
        0,
        "Very frail patients can get 25 Gy in 5 (Roa), TMZ alone if MGMT-methylated (Nordic, NOA-08), or supportive care."),
      fill("Late toxicity",
        "Which late toxicity is she at risk for with a left temporal target?",
        "Memory and language decline (left temporal lobe and hippocampus), fatigue, and steroid side effects.",
        "Discuss goals of care alongside treatment."),
      fill("Steroids",
        "She is on dexamethasone for edema. Which steroid side effects should you watch for?",
        "High blood sugar, insomnia and mood changes, weight gain, thrush, proximal muscle weakness, GI upset or ulcers, infections, and bone loss.",
        "Taper to the lowest dose that controls symptoms."),
    ],
  },
  {
    "id": "cns-case-3", "level": "Advanced",
    "title": "Case 6: The First Seizure",
    "oneLiner": "A 38-year-old man has his first seizure. MRI shows a 5 cm non-enhancing, FLAIR-bright left frontal mass, and CT shows calcification in it.",
    "steps": [
      mcq("Diagnosis",
        "Which diagnosis fits best?",
        ["Glioblastoma", "Oligodendroglioma", "Meningioma", "Brain metastasis"],
        1,
        "A young adult with a seizure and a frontal, cortical, non-enhancing, calcified tumor is an oligodendroglioma until proven otherwise.",
        image="images/cns/cns-lgg-flair.jpg",
        caption="Axial FLAIR MRI of a non-enhancing low-grade glioma in the left frontal and insular region (another patient). Vail M et al., Cureus 2026 (PMC12947947), CC BY 4.0."),
      fill("Pathology",
        "What is the integrated diagnosis?",
        "Oligodendroglioma, IDH-mutant and 1p/19q-codeleted, WHO grade 2",
        "IDH mutation plus 1p/19q codeletion defines oligodendroglioma. IDH-mutant without codeletion is astrocytoma.",
        context="<p><strong>Subtotal resection</strong> (residual non-enhancing tumor near the motor strip). <strong>Pathology:</strong> <strong>IDH-mutant, 1p/19q codeleted</strong>, WHO grade 2.</p>"),
      fill("Options",
        "Name two reasonable next steps given his residual tumor.",
        "Vorasidenib to delay RT and chemo, or RT 50.4-54 Gy followed by PCV; close MRI surveillance with either approach.",
        "Residual tumor makes him higher risk. Vorasidenib is for residual or recurrent non-enhancing grade 2 IDH-mutant tumors."),
      mcq("Trial",
        "Which trial showed that RT plus PCV nearly doubled median overall survival (13.3 vs 7.8 years) in high-risk grade 2 gliomas?",
        ["RTOG 9802", "INDIGO", "CATNON", "Stupp"],
        0,
        "RTOG 9802 is the RT plus PCV trial. INDIGO showed vorasidenib delayed progression (PFS about 28 vs 11 months); CATNON is the grade 3 non-codeleted astrocytoma trial.",
        tag=TRIAL),
      fill("Dose",
        "If RT is given, what dose and chemo?",
        "About 54 Gy in 30 fractions (50.4-54 Gy), followed by PCV (procarbazine, lomustine, vincristine).",
        "Grade 3 oligodendroglioma would get 59.4 Gy plus PCV."),
      mcq("Survivorship",
        "Why do late effects matter more for him than for a GBM patient, and what can reduce them?",
        ["They don't matter", "He may live decades, so memory, fatigue, and endocrine effects matter; hippocampal sparing and protons are often considered", "He needs whole-brain RT instead", "Late effects only happen in children"],
        1,
        "Lower-grade glioma patients live years to decades, so the plan weighs long-term cognition and quality of life."),
    ],
  },
  {
    "id": "cns-case-5", "level": "Advanced",
    "title": "Case 7: Vomiting and Unsteady",
    "oneLiner": "A 64-year-old man with metastatic melanoma on immunotherapy has 4 days of vomiting, headache, and unsteadiness.",
    "steps": [
      mcq("Next step",
        "MRI shows a single 4 cm right cerebellar metastasis compressing the 4th ventricle, with early hydrocephalus. What is the next step?",
        ["SRS alone", "Surgical resection", "Whole-brain RT", "Observation on immunotherapy"],
        1,
        "A large lesion with mass effect and hydrocephalus needs surgery to relieve pressure quickly. SRS alone is for smaller lesions without dangerous mass effect."),
      mcq("Adjuvant",
        "Gross total resection leaves a 3.5 cm cavity, with no other brain lesions. What adjuvant treatment is standard?",
        ["Observation", "SRS/SRT to the resection cavity", "Whole-brain RT", "Craniospinal RT"],
        1,
        "Cavity SRS lowers the local recurrence risk after resection while sparing cognition."),
      mcq("Trial",
        "Which trials support cavity SRS: better local control than observation, and better cognition than whole-brain RT?",
        ["Mahajan and NCCTG N107C", "JLGK0901", "NRG CC001", "Patchell"],
        0,
        "Mahajan compared cavity SRS with observation; N107C compared it with WBRT.",
        tag=TRIAL),
      fill("Regimen",
        "Give a common regimen for a 3.5 cm cavity.",
        "Fractionated SRT, for example 27 Gy in 3 or 30 Gy in 5 fractions, to the cavity plus 1-2 mm (including the surgical tract and adjacent dura).",
        "Large cavities are fractionated to lower the risk of radionecrosis.",
        image="images/cns/cns-srs-plan.jpg",
        caption="Fractionated SRS plan for a resection cavity (24 Gy in 3 fractions) and a separate intact metastasis, in another patient: prescription isodose in green. Lewis J et al., Cureus 2025 (PMC12414254), CC BY 4.0."),
      mcq("Risk",
        "Which part of his treatment raises the risk of radionecrosis with SRS?",
        ["Antiemetics", "Checkpoint inhibitor immunotherapy given around the time of SRS", "Antiseizure medicine", "Physical therapy"],
        1,
        "Immunotherapy and larger target volumes both raise the radionecrosis risk."),
      fill("Eight months later",
        "Eight months later he has new headaches and MRI shows growing enhancement with a lot of edema at the cavity edge. How do you approach it?",
        "Consider radionecrosis vs recurrence: advanced imaging (perfusion MRI, PET) or tissue to tell them apart. Treat symptomatic necrosis with steroids, then bevacizumab or laser ablation if needed; recurrence may need surgery or re-irradiation.",
        ""),
    ],
  },
  {
    "id": "cns-case-8", "level": "Advanced",
    "title": "Case 8: Back Pain and Weak Legs",
    "oneLiner": "A 67-year-old man with metastatic prostate cancer has 2 weeks of worsening mid-back pain and 1 day of leg weakness and trouble walking.",
    "steps": [
      mcq("First move",
        "What is the first thing to do?",
        ["Order outpatient X-rays", "Give dexamethasone and get an urgent MRI of the whole spine", "Start physical therapy", "Schedule palliative RT next week"],
        1,
        "New neurologic deficits with back pain in a cancer patient are cord compression until proven otherwise. Steroids now, and MRI of the whole spine because other levels are often involved."),
      mcq("Grade",
        "MRI shows a T10 metastasis with epidural tumor compressing the cord and no CSF visible around it at that level. What is the Bilsky grade?",
        ["Bilsky 0", "Bilsky 1b", "Bilsky 2", "Bilsky 3"],
        3,
        "Bilsky 3 is cord compression with no CSF visible around the cord; 2 is compression with some CSF remaining; 1 is epidural disease without cord deformity. 2-3 is high-grade compression.",
        image="images/cns/cns-spine-mri.jpg",
        caption="Sagittal T2 MRI of the thoracic spine in another patient: a pathologic fracture with epidural tumor compressing the cord. Kuah T et al., Cancers 2022 (PMC9265325), CC BY 4.0."),
      mcq("Plan",
        "He is medically fit, has one level of compression, and the spine is stable. What's the plan?",
        ["RT alone", "Urgent surgical decompression (stabilization if needed), then postoperative RT, with steroids", "Steroids alone", "Hospice"],
        1,
        "For fit patients with a single level of high-grade compression, surgery plus RT keeps more patients walking."),
      mcq("Trial",
        "Which trial showed more patients kept or regained the ability to walk with surgery plus RT than with RT alone?",
        ["Patchell (2005)", "QUARTZ", "JLGK0901", "RTOG 9802"],
        0,
        "Patchell is why fit patients with cord compression get a surgical consult.",
        tag=TRIAL),
      fill("Regimens",
        "Give RT regimens used for cord compression.",
        "8 Gy in 1, 20 Gy in 5, or 30 Gy in 10 fractions (after surgery, often 20-30 Gy); SBRT (for example 24 Gy in 2) for selected radioresistant or oligometastatic disease.",
        "Choose by prognosis, histology, and whether surgery was done."),
      mcq("Prognosis",
        "What is the strongest predictor of whether he walks after treatment?",
        ["His PSA", "Whether he can walk before treatment", "The RT machine used", "His age"],
        1,
        "Ambulatory status at the start of treatment is the strongest predictor, which is why cord compression is treated as an emergency."),
    ],
  },
]

INTRO = "<p>Eight cases that get harder as you go: <strong>benign tumors</strong> (vestibular schwannoma, meningioma), <strong>brain metastases</strong>, <strong>gliomas</strong>, and <strong>spinal cord compression</strong>. Each starts with a one-liner, then gives you more information step by step: the <strong>MRI and pathology</strong>, the <strong>diagnosis or grade</strong>, the <strong>treatment</strong>, the <strong>dose and targets</strong>, the <strong>landmark trials</strong>, and the <strong>side effects and follow-up</strong>. Some steps are multiple choice, some are fill-in-the-blank.</p>"

if __name__ == "__main__":
    write("cns", INTRO, CASES)
