"""Source for src/data/cases/gi.json. Run: python3 tools/cases/gi_cases.py"""
from casekit import TRIAL, mcq, fill, write

CASES = [
  {
    "id": "gi-case-1", "level": "Foundational",
    "title": "Case 1: Not Hemorrhoids",
    "oneLiner": "A 58-year-old woman has had 6 months of anal bleeding and pain, treated as hemorrhoids. Exam finds a firm 3.5 cm mass in the anal canal. Her groins feel normal.",
    "steps": [
      mcq("Workup",
        "Biopsy shows squamous cell carcinoma. Which set of tests comes next?",
        ["Colonoscopy only", "CT chest/abdomen/pelvis ± PET/CT, pelvic MRI, an HIV test, and a gynecologic exam", "Bone scan and brain MRI", "No staging needed; go to surgery"],
        1,
        "Anal cancer is HPV-driven, so check HIV and screen the cervix. MRI defines the primary and pelvic nodes; PET/CT finds groin and distant disease. Always examine the groins.",
        image="images/gi/gi-c-anal.jpg",
        caption="A carcinoma of the anal canal on exam, easy to mistake for a hemorrhoid. Dr. K.-H. Günther, Wikimedia Commons, CC BY 3.0."),
      fill("Stage",
        "What are the T and N stage?",
        "T2 N0",
        "Anal T stage is size: T1 2 cm or less, T2 over 2 and up to 5 cm, T3 over 5 cm, T4 invades adjacent organs (vagina, urethra, bladder), whatever the size. Sphincter invasion does not count as T4.",
        context="<p><strong>MRI:</strong> 3.5 cm anal canal tumor invading the internal sphincter; vagina clear. <strong>PET/CT:</strong> no nodal or distant disease. HIV negative.</p>"),
      mcq("Treatment",
        "What is the treatment?",
        ["Abdominoperineal resection (APR)", "Definitive chemoRT: IMRT with 5-FU (or capecitabine) and mitomycin; surgery only for salvage", "Chemotherapy alone", "Local excision"],
        1,
        "Anal cancer is the one GI site where chemoRT, not surgery, is the cure, and most patients keep their sphincter. APR is saved for persistent or recurrent disease."),
      mcq("Trial",
        "Which trial showed that mitomycin with 5-FU and RT beat induction plus concurrent cisplatin?",
        ["RTOG 9811", "CROSS", "RAPIDO", "German CAO/ARO/AIO-94"],
        0,
        "Nigro first showed chemoRT could replace APR. RTOG 9811 favored mitomycin, and ACT II confirmed cisplatin was no better and maintenance chemo didn't help.",
        tag=TRIAL),
      fill("Dose",
        "Give the RTOG 0529 doses for her T2 N0 tumor.",
        "Primary 50.4 Gy in 28 fractions; elective nodes (inguinal and pelvic) 42 Gy in 28 fractions.",
        "Every patient has the groins and pelvic nodes treated, even when node-negative.",
        image="images/gi/gi-g-rtog-atlas.jpg",
        caption="Elective nodal CTV (yellow) for anal cancer on axial CT slices, from L5 down to the inguinal nodes. Dapper H et al., BMC Cancer 2019 (PMC6664500), CC BY 4.0."),
      mcq("Response",
        "Eight weeks after chemoRT, a small firm area is still felt. What do you do?",
        ["APR now", "Keep watching: responses can keep improving up to 26 weeks after starting; biopsy only if it persists or grows", "Re-irradiate", "Start palliative chemo"],
        1,
        "ACT II showed many complete responses only appear by 26 weeks. Operating too early leads to unnecessary APRs."),
      fill("Side effects",
        "What side effects do you counsel her about?",
        "Acute: a severe skin reaction in the perineum and groins, diarrhea, painful urination, fatigue, and low counts from mitomycin. Late: fibrosis, vaginal narrowing and sexual dysfunction (dilators), infertility and early menopause, bowel urgency, and pelvic insufficiency fractures.",
        "Avoid treatment breaks: they lower cure rates."),
    ],
  },
  {
    "id": "gi-case-5", "level": "Foundational",
    "title": "Case 2: Food That Won't Go Down",
    "oneLiner": "A 63-year-old man with obesity and long-standing heartburn has 3 months of trouble swallowing solids and a 12 lb weight loss.",
    "steps": [
      mcq("Background",
        "Upper endoscopy shows salmon-colored mucosa reaching up from the GE junction and a mass at 36-41 cm. What is the precursor, and what cancer type is most likely?",
        ["Leukoplakia; squamous cell carcinoma", "Barrett's esophagus; adenocarcinoma", "Achalasia; small cell carcinoma", "Celiac disease; lymphoma"],
        1,
        "Reflux and obesity drive Barrett's metaplasia and distal adenocarcinoma. Smoking and alcohol drive squamous cell carcinoma, usually higher in the esophagus.",
        image="images/gi/gi-g-barrett.jpg",
        caption="Barrett's esophagus: salmon-colored columnar mucosa extending above the GE junction (arrows mark the top of the gastric folds). Japan Esophageal Society, Esophagus 2017 (PMC5222925), CC BY 4.0."),
      mcq("T stage",
        "Which test best defines the T stage?",
        ["CT", "Endoscopic ultrasound (EUS)", "Barium swallow", "Colonoscopy"],
        1,
        "EUS shows the wall layers and nearby nodes. PET/CT checks for distant disease.",
        image="images/gi/gi-eus.jpg",
        caption="High-frequency EUS of a normal esophageal wall with a schematic of its layers. Yun SM et al., J Korean Soc Radiol 2024 (PMC11473974), CC BY-NC 4.0."),
      fill("Stage",
        "What is his clinical stage?",
        "cT3 N1 M0 adenocarcinoma",
        "Through the muscularis into the adventitia is T3; 1-2 regional nodes is N1.",
        context="<p><strong>EUS:</strong> tumor through the muscularis into the adventitia; 2 periesophageal nodes. <strong>PET/CT:</strong> avid primary and nodes, no distant disease. HER2 negative, MMR proficient. Fit for surgery.</p>"),
      mcq("Trial",
        "Which trial established 41.4 Gy in 23 fractions with weekly carboplatin and paclitaxel before esophagectomy, nearly doubling median survival?",
        ["CROSS", "RTOG 9405", "FLOT4", "CheckMate 577"],
        0,
        "CROSS gave a pCR rate of 29% overall (49% in squamous cell). For adenocarcinoma, perioperative FLOT is an alternative; ESOPEC found better survival with FLOT than CROSS.",
        tag=TRIAL),
      fill("Dose",
        "Give the CROSS dose and a key lung constraint.",
        "41.4 Gy in 23 fractions with weekly carboplatin and paclitaxel; keep lung V20 under about 20% to limit lung complications after surgery.",
        "Heart dose matters too for distal tumors."),
      mcq("After surgery",
        "After CROSS and esophagectomy, the specimen still has residual cancer. What is added?",
        ["Nothing", "Adjuvant nivolumab for 1 year", "More radiation", "Trastuzumab"],
        1,
        "CheckMate 577 showed better disease-free survival with adjuvant nivolumab for residual disease after neoadjuvant chemoRT and surgery."),
      fill("Side effects",
        "What side effects during chemoRT should you plan for?",
        "Esophagitis (painful swallowing from about week 2-3) with weight loss, so nutrition support (sometimes a feeding tube), plus fatigue and low counts; later, lung and heart effects.",
        ""),
    ],
  },
  {
    "id": "gi-case-3", "level": "Intermediate",
    "title": "Case 3: The Low One",
    "oneLiner": "A 54-year-old man has 2 months of rectal bleeding. Colonoscopy finds an adenocarcinoma 4 cm from the anal verge. It is MMR proficient.",
    "steps": [
      mcq("Imaging",
        "Which study best stages the primary?",
        ["CT abdomen and pelvis", "High-resolution pelvic MRI", "PET/CT", "Barium enema"],
        1,
        "Rectal MRI shows the depth of spread, the distance to the mesorectal fascia (MRF), EMVI, nodes, and the relation to the sphincters. CT chest/abdomen/pelvis checks for metastases.",
        image="images/gi/gi-rmri-emvi.jpg",
        caption="T2 MRI of a low rectal cancer in three planes: extramural venous invasion (red arrows), and tumor deposits (green) vs a malignant node (blue). Curcean S et al., Cancers 2024 (PMC11394290), CC BY 4.0."),
      fill("Stage",
        "Summarize the stage and the high-risk features.",
        "cT3c N1b M0 (stage III) with a threatened MRF, EMVI, and a low location.",
        "MRF 1 mm or less is threatened. EMVI and a low tumor raise the risk of local and distant recurrence.",
        context="<p><strong>MRI:</strong> T3c tumor, lower edge 4 cm from the verge, <strong>0.5 mm from the MRF</strong>, EMVI positive, 3 suspicious mesorectal nodes. <strong>CT:</strong> no metastases. CEA 6.</p>"),
      mcq("Approach",
        "Which approach is best?",
        ["Surgery first, then decide", "Total neoadjuvant therapy (chemoRT plus about 4 months of chemo), then TME or watch-and-wait", "Short-course RT alone", "Chemo alone"],
        1,
        "High-risk rectal cancer gets total neoadjuvant therapy. Long-course chemoRT is preferred for a threatened MRF or T4."),
      mcq("Trial",
        "Which trial first showed that preoperative chemoRT beat postoperative chemoRT, cutting local recurrence (6% vs 13%) with less toxicity?",
        ["German CAO/ARO/AIO-94", "RAPIDO", "PROSPECT", "OPRA"],
        0,
        "The German rectal trial made neoadjuvant treatment the standard. RAPIDO and PRODIGE 23 then supported total neoadjuvant therapy; OPRA showed organ preservation; PROSPECT allowed selective RT omission for lower-risk tumors.",
        tag=TRIAL),
      fill("Dose and nodes",
        "Give the long-course chemoRT dose and the nodes you would cover.",
        "45 Gy to the pelvis with a boost to 50.4-54 Gy (28-30 fractions) and capecitabine; cover the tumor, the whole mesorectum, and the presacral, internal iliac, and obturator nodes.",
        "Add external iliac nodes for T4 tumors into anterior organs, and inguinal nodes if the anal canal is involved.",
        image="images/gi/gi-ax-rectum.jpg",
        caption="Axial T2 MRI of a T3 rectal cancer reaching the left mesorectal fascia. Pikūnienė I et al., Cureus 2023 (PMC10493462), CC BY 4.0."),
      mcq("Restaging",
        "After TNT, endoscopy shows a flat white scar and MRI shows only dark fibrosis. What option does he have?",
        ["APR is mandatory", "Watch-and-wait with close MRI and endoscopy surveillance, keeping his rectum", "More chemo indefinitely", "Re-irradiation"],
        1,
        "A clinical complete response allows watch-and-wait. In OPRA, about half of patients kept their rectum; regrowth, usually in the first 2 years, is salvaged with TME.",
        image="images/gi/gi-c-scar.jpg",
        caption="Restaging T2 MRI after treatment: a dark, fibrotic full-thickness scar (arrow) with no regrowth on 4-year follow-up. Ortega CD, Perez RO, Insights Imaging 2019 (PMC6542937), CC BY 4.0."),
      fill("Late effects",
        "If he had a low anterior resection instead, what bowel problem would you warn him about?",
        "Low anterior resection syndrome: urgency, frequency, clustering, and incontinence, worse after pelvic RT. Other late effects: sexual and urinary dysfunction and infertility (sperm banking before treatment).",
        ""),
    ],
  },
  {
    "id": "gi-case-2", "level": "Intermediate",
    "title": "Case 4: The Groin Node",
    "oneLiner": "A 51-year-old man with HIV (CD4 520, undetectable viral load) has a 6 cm anal canal cancer and a firm 2.5 cm left groin node.",
    "steps": [
      mcq("HIV",
        "How does his HIV status change treatment?",
        ["He should get RT alone", "He gets standard chemoRT, since his CD4 count is good and HIV is controlled", "He needs an APR", "Chemo doses must be halved"],
        1,
        "Well-controlled HIV patients get standard chemoRT. Keep antiretrovirals going and watch counts closely."),
      fill("Stage",
        "What is his TNM stage and group?",
        "T3 N1a M0, Stage IIIC",
        "Over 5 cm is T3. Inguinal, mesorectal, or internal iliac nodes are N1a; external iliac N1b; both N1c.",
        context="<p><strong>PET/CT:</strong> 6 cm avid anal canal tumor; avid 2.5 cm left inguinal node (FNA positive); no external iliac or distant disease.</p>",
        image="images/gi/gi-apet.jpg",
        caption="Fused FDG PET/CT of anal cancer in another patient: (a) primary, (b) avid inguinal node, (c) external iliac node. Koppula BR et al., Cancers 2022 (PMC9179927), CC BY 4.0."),
      mcq("Treatment",
        "Which treatment?",
        ["APR with groin dissection", "Definitive chemoRT with 5-FU or capecitabine plus mitomycin", "Chemo alone", "RT alone"],
        1,
        "Node-positive anal cancer is still treated with definitive chemoRT."),
      fill("Doses",
        "Give the RTOG 0529 doses for the primary, the involved node, and the elective nodes.",
        "Primary 54 Gy in 30; involved node 3 cm or less 50.4 Gy in 30 (over 3 cm, 54 Gy); elective nodes 45 Gy in 30.",
        "Dose painting with IMRT spares the skin, bowel, bladder, and genitals compared with older 3D plans."),
      mcq("Acute toxicity",
        "Which acute side effect drove the move to IMRT in RTOG 0529?",
        ["Hearing loss", "Severe skin, GI, and GU toxicity and blood count drops (with fewer treatment breaks on IMRT)", "Pneumonitis", "Hair loss"],
        1,
        "IMRT reduced severe skin and GI toxicity compared with older techniques, which helps patients avoid breaks."),
      fill("Eight months later",
        "Eight months later he has new pain in his lower back and hip when walking; there is no sign of recurrence. What late effect should you consider, and what else would you counsel him about?",
        "A pelvic insufficiency fracture (sacrum or pubic rami) from RT to the pelvic bones. Also counsel on sexual dysfunction, infertility (sperm banking before treatment), bowel urgency, and skin fibrosis.",
        "MRI or CT shows the fracture; it is usually managed conservatively."),
    ],
  },
  {
    "id": "gi-case-6", "level": "Intermediate",
    "title": "Case 5: Not a Surgical Candidate",
    "oneLiner": "A 72-year-old heavy smoker and drinker with severe COPD has trouble swallowing. Endoscopy finds a mid-thoracic esophageal squamous cell carcinoma (27-33 cm).",
    "steps": [
      mcq("Bronchoscopy",
        "Bronchoscopy is ordered. Why?",
        ["To check for asthma", "To rule out tracheal or bronchial invasion or a fistula", "To biopsy the lung", "It isn't needed"],
        1,
        "Mid- and upper-thoracic tumors sit right behind the trachea and left main bronchus. Airway invasion (T4b) or a fistula changes the plan."),
      fill("Biology",
        "PET/CT shows a 6 cm tumor with a subcarinal node and no distant disease; the airway is clear. What is special about squamous cell carcinoma and chemoRT?",
        "Squamous cell carcinoma is more radiosensitive (pCR about 49% with CROSS vs about 23% for adenocarcinoma), so definitive chemoRT is a real curative option.",
        "",
        image="images/gi/gi-epet.jpg",
        caption="Coronal CT (A) and FDG PET/CT (B) of a mid-esophageal cancer (white arrows) with avid nodes. Tashiro H et al., Surg Case Rep 2025 (PMC12702577), CC BY 4.0."),
      mcq("Treatment",
        "He is a poor surgical candidate. What is the treatment?",
        ["Esophagectomy anyway", "Definitive chemoRT", "Stent only", "RT alone without chemo"],
        1,
        "RTOG 8501 showed chemoRT beat RT alone for esophageal cancer."),
      mcq("Trial",
        "Which trial showed that raising the dose to 64.8 Gy was no better than 50.4 Gy?",
        ["RTOG 9405 (INT 0123)", "CROSS", "RTOG 8501", "ESOPEC"],
        0,
        "Definitive chemoRT for esophageal cancer uses 50-50.4 Gy.",
        tag=TRIAL),
      fill("Constraints",
        "Which organs at risk matter most for a mid-esophageal plan?",
        "Lungs (especially with his COPD: keep V20 and mean lung dose low), heart, spinal cord, and, for distal tumors, the liver and kidneys.",
        ""),
      mcq("Follow-up",
        "Six months later he has trouble swallowing again, but endoscopy shows a narrow, smooth segment with no tumor. What is it?",
        ["Recurrence", "A benign radiation stricture, treated with dilation", "A tracheoesophageal fistula", "Achalasia"],
        1,
        "Strictures are a common late effect of esophageal chemoRT. Biopsy any mass or ulcer, since recurrence can look similar."),
    ],
  },
  {
    "id": "gi-case-7", "level": "Advanced",
    "title": "Case 6: Yellow Eyes",
    "oneLiner": "A 66-year-old man has painless yellowing of his eyes and skin, dark urine, pale stools, and a 10 lb weight loss.",
    "steps": [
      mcq("Workup",
        "CT shows dilated bile and pancreatic ducts (a 'double duct sign'). Which study should be done next to judge resectability?",
        ["MRI of the brain", "Pancreatic-protocol (multiphase) CT, ideally before a biliary stent", "Colonoscopy", "Bone scan"],
        1,
        "Painless jaundice with a double duct sign is pancreatic head cancer until proven otherwise. A pancreatic-protocol CT defines vessel contact; stents can blur the picture, so image first when possible. EUS gives tissue.",
        image="images/gi/gi-c-jaundice.jpg",
        caption="Scleral icterus (yellow eyes) from jaundice. CDC/Dr. Thomas F. Sellers, Wikimedia Commons, public domain."),
      mcq("Resectability",
        "CT shows a 3 cm pancreatic head mass with 200° of SMV contact and a short narrowed segment that can be reconstructed, no arterial contact, and no liver lesions. What category?",
        ["Resectable", "Borderline resectable", "Locally advanced", "Metastatic"],
        1,
        "Vein contact over 180° or narrowing that can still be reconstructed is borderline. Over 180° arterial encasement (SMA, celiac) or an unreconstructable vein is locally advanced.",
        image="images/gi/gi-pct.jpg",
        caption="Portal venous phase CT of a hypoenhancing pancreatic head mass (red arrow) next to the SMV, with a biliary stent. Louis M et al., Cureus 2025 (PMC11981547), CC BY 4.0."),
      fill("Plan",
        "What is the plan?",
        "Biliary stent for the jaundice; neoadjuvant mFOLFIRINOX (± chemoRT or SBRT); restage; then a Whipple with vein resection if feasible, followed by more chemo.",
        "Germline testing is done for every pancreatic cancer (BRCA status changes systemic options)."),
      mcq("Trial",
        "Which trial showed that adjuvant mFOLFIRINOX after resection improved median survival (about 54 vs 35 months)?",
        ["PRODIGE 24", "LAP07", "RTOG 1112", "CROSS"],
        0,
        "Chemo leads in pancreatic cancer. LAP07 showed chemoRT for locally advanced disease improved local control but not survival; PREOPANC supported neoadjuvant chemoRT.",
        tag=TRIAL),
      fill("SBRT",
        "If SBRT is used, what dose range, and which organs limit it?",
        "About 33-40 Gy in 5 fractions; the duodenum, stomach, and bowel right next to the pancreas (bleeding, ulcer, perforation) limit the dose.",
        ""),
      mcq("Palliation",
        "If the disease had been unresectable with severe back pain, which RT option helps pain?",
        ["Whole-brain RT", "RT to the tumor and celiac plexus region", "Prophylactic cranial RT", "None; RT never helps pancreatic pain"],
        1,
        "Pancreatic pain often comes from tumor at the celiac plexus; RT to that region (or a celiac plexus block) can relieve it."),
    ],
  },
  {
    "id": "gi-case-8", "level": "Advanced",
    "title": "Case 7: The Surveillance Ultrasound",
    "oneLiner": "A 64-year-old man with hepatitis C cirrhosis (Child-Pugh A6) has a new 4 cm liver lesion on his routine surveillance ultrasound. His AFP is 180.",
    "steps": [
      mcq("Diagnosis",
        "Multiphase MRI shows arterial hyperenhancement, washout, and a capsule. What is the next step?",
        ["Biopsy is always required", "Diagnose HCC (LI-RADS 5) without a biopsy", "PET/CT", "Repeat ultrasound in 6 months"],
        1,
        "In a cirrhotic liver, classic arterial enhancement plus washout (LI-RADS 5) is diagnostic of HCC; biopsy is not required.",
        image="images/gi/gi-hcc.jpg",
        caption="Multiphase CT of HCC in another patient: (A) arterial hyperenhancement, (B) washout on the delayed phase, with tumor extending into the right portal vein. Han JE et al., J Liver Cancer 2021 (PMC10035689), CC BY-NC 4.0."),
      fill("Staging",
        "What BCLC stage is he, and why does Child-Pugh matter for RT?",
        "BCLC A (single tumor, preserved liver function, performance status 0). Child-Pugh A (to B7) patients can get SBRT with a lower risk of liver toxicity.",
        "Liver function, not just the tumor, decides what can be offered.",
        context="<p><strong>MRI:</strong> 4 cm segment VII HCC abutting the IVC, not suited to ablation; no vascular invasion or extrahepatic disease. Resection declined (portal hypertension). Transplant evaluation is under way.</p>"),
      mcq("Option",
        "Which is a reasonable radiation option?",
        ["Whole-liver RT", "SBRT, for example as a bridge to transplant", "No RT is ever used for HCC", "Brachytherapy"],
        1,
        "SBRT is used for tumors not suited to ablation, as a bridge to transplant, and for portal vein tumor thrombus. TACE and Y-90 are other liver-directed options."),
      mcq("Trial",
        "Which trial showed that adding SBRT to sorafenib improved overall and progression-free survival in unresectable HCC?",
        ["RTOG 1112", "LAP07", "PRODIGE 24", "OPRA"],
        0,
        "RTOG 1112 made SBRT a real option for HCC.",
        tag=TRIAL),
      fill("Dose",
        "Give an SBRT dose range and the normal liver constraint.",
        "About 30-50 Gy in 3-5 fractions; keep at least 700 cc of normal liver under 15 Gy (and respect stomach and duodenum limits).",
        ""),
      mcq("Toxicity",
        "Two months after SBRT he develops ascites, an enlarged liver, and a rising alkaline phosphatase, without tumor progression. What is it?",
        ["Radiation-induced liver disease (RILD)", "Pneumonitis", "Normal healing", "Hepatitis C flare only"],
        0,
        "RILD usually appears weeks to a few months after RT, with anicteric ascites and hepatomegaly. Poor baseline liver function raises the risk, which is why Child-Pugh and liver dose limits matter."),
    ],
  },
  {
    "id": "gi-case-4", "level": "Advanced",
    "title": "Case 8: The Family History",
    "oneLiner": "A 38-year-old woman whose mother had endometrial cancer at 46 and whose uncle had colon cancer at 42 has a mid-rectal adenocarcinoma, cT3 N1.",
    "steps": [
      mcq("Key test",
        "Which test result would most change her treatment?",
        ["CEA", "MMR/MSI status", "KRAS", "HER2"],
        1,
        "MMR-deficient (MSI-high) rectal cancers respond dramatically to checkpoint inhibitors, which can replace chemoRT and surgery."),
      mcq("Syndrome",
        "IHC shows loss of MSH2 and MSH6 (MMR-deficient). Which syndrome should she be tested for?",
        ["Li-Fraumeni", "Lynch syndrome (germline MMR testing)", "BRCA", "FAP"],
        1,
        "Young age, a family history of colorectal and endometrial cancer, and an MMR-deficient tumor all point to Lynch syndrome. Her relatives can be tested, and she needs endometrial and ovarian cancer risk management too.",
        context="<p><strong>MRI:</strong> mid-rectal T3b tumor, MRF clear, 2 mesorectal nodes. <strong>IHC:</strong> loss of MSH2/MSH6 (<strong>MMR-deficient</strong>).</p>",
        image="images/gi/gi-rmri-ax.jpg",
        caption="Axial T2 MRI of two rectal cancers with the mesorectal fascia traced: (a) T3ab with the MRF clear, (b) T3cd reaching the MRF. Bogveradze N et al., Insights Imaging 2023 (PMC9849549), CC BY 4.0."),
      mcq("Trial",
        "Which study showed that dostarlimab alone produced complete clinical responses in essentially every patient with MMR-deficient locally advanced rectal cancer?",
        ["Cercek et al. (dostarlimab)", "RAPIDO", "PROSPECT", "CROSS"],
        0,
        "Every patient in the Cercek study had a clinical complete response and avoided radiation and surgery, at least initially.",
        tag=TRIAL),
      mcq("First treatment",
        "What is her first treatment?",
        ["TNT then TME", "A checkpoint inhibitor (dostarlimab)", "Short-course RT", "Upfront TME"],
        1,
        "Checkpoint inhibitor first for dMMR rectal cancer, with close MRI and endoscopic surveillance."),
      fill("If incomplete",
        "If she didn't respond fully to immunotherapy, what would come next?",
        "Standard chemoRT or TNT, then TME; radiation and surgery are still available.",
        ""),
      fill("Why it matters",
        "She is 38 and hopes to have children. Why is avoiding pelvic RT so valuable for her?",
        "Pelvic RT would likely cause ovarian failure and infertility (and affect the uterus), plus sexual, bowel, and bladder late effects. Immunotherapy alone avoids these.",
        "If pelvic RT were needed, fertility preservation (egg or embryo freezing, ovarian transposition) would be discussed first."),
    ],
  },
]

INTRO = "<p>Eight cases that get harder as you go, across the anus, esophagus, rectum, pancreas, and liver. Each starts with a one-liner, then gives you more information step by step: the <strong>exam, endoscopy, MRI, and PET</strong>, the <strong>stage</strong>, where radiation fits around <strong>surgery and chemo</strong>, the <strong>dose and targets</strong>, the <strong>landmark trials</strong>, and the <strong>side effects and follow-up</strong>. Some steps are multiple choice, some are fill-in-the-blank.</p>"

if __name__ == "__main__":
    write("gi", INTRO, CASES)
