"""Source for src/data/cases/gyn.json. Run: python3 tools/cases/gyn_cases.py"""
from casekit import TRIAL, mcq, fill, write

CASES = [
  {
    "id": "gyn-case-5", "level": "Foundational",
    "title": "Case 1: Bleeding After Menopause",
    "oneLiner": "A 66-year-old woman who went through menopause 14 years ago has had three episodes of vaginal spotting. She has obesity and type 2 diabetes.",
    "steps": [
      mcq("Workup",
        "What is the best first workup for postmenopausal bleeding?",
        ["CT of the abdomen and pelvis", "Transvaginal ultrasound and/or endometrial biopsy", "Pap smear only", "Reassurance"],
        1,
        "Postmenopausal bleeding is endometrial cancer until proven otherwise. A thickened endometrial stripe on transvaginal ultrasound or an endometrial biopsy gives the answer. Obesity and diabetes (excess estrogen) are classic risk factors."),
      mcq("Molecular",
        "Biopsy shows endometrioid adenocarcinoma, and she has a hysterectomy, BSO, and sentinel node biopsy. Which tests are now done on every endometrial cancer?",
        ["HER2 and ER", "MMR/MSI, p53, and POLE", "p16 and HPV", "PD-L1 only"],
        1,
        "The molecular class (POLE-mutated, MMR-deficient, p53-abnormal, or no specific molecular profile) now shapes adjuvant treatment. MMR deficiency also prompts Lynch syndrome screening."),
      fill("Stage",
        "What is her FIGO stage?",
        "Stage IB",
        "Myometrial invasion of 50% or more is IB; under 50% is IA. Cervical stromal invasion would be stage II. For a low-grade endometrioid tumor without substantial LVSI, FIGO 2023 gives the same stage as the 2009 anatomic system.",
        context="<p><strong>Pathology:</strong> grade 2 endometrioid, <strong>60% myometrial invasion</strong>, no cervical stromal invasion, no LVSI, sentinel nodes negative. <strong>Molecular:</strong> no specific molecular profile (NSMP).</p>"),
      mcq("Adjuvant",
        "What adjuvant treatment fits best?",
        ["Observation only", "Vaginal brachytherapy", "Pelvic EBRT plus chemo", "Whole-abdomen RT"],
        1,
        "Deep invasion makes her recurrence risk intermediate, and most of that risk is at the vaginal cuff, so vaginal brachytherapy (or observation) is the usual choice. Her NSMP molecular group doesn't move her up or down."),
      mcq("Trial",
        "Which trial showed vaginal brachytherapy controlled vaginal recurrence as well as pelvic EBRT, with far less GI toxicity?",
        ["PORTEC-2", "PORTEC-3", "GOG 258", "LACC"],
        0,
        "PORTEC-1 and GOG 99 showed pelvic RT cut (mostly vaginal) recurrence without improving survival; PORTEC-2 then showed the cylinder was enough for intermediate-risk patients.",
        tag=TRIAL),
      fill("Dose",
        "Give a typical vaginal brachytherapy prescription.",
        "HDR 7 Gy in 3 fractions prescribed to 0.5 cm depth, treating the upper vagina (about 3-5 cm).",
        "When given after pelvic EBRT, the cylinder dose is lower, for example 5-6 Gy in 2-3 fractions."),
      mcq("Counseling",
        "Which long-term side effect will you counsel her about, and what is this device for?",
        ["Hearing loss; it is an earplug", "Vaginal dryness and narrowing (stenosis); a dilator used regularly keeps the vagina open for exams and comfort", "Bladder stones; it is a catheter", "Lymphedema; it is a compression sleeve"],
        1,
        "Vaginal brachytherapy has few side effects; dryness and stenosis are the main ones. Regular dilator use and lubricants help.",
        image="images/gyn/gyn-c-dilator.jpg",
        caption="A vaginal dilator. Moon H, Korean J Women Health Nurs 2023 (PMC10788390), CC BY 4.0."),
    ],
  },
  {
    "id": "gyn-case-1", "level": "Foundational",
    "title": "Case 2: After the Surgery",
    "oneLiner": "A 41-year-old woman has a 3 cm squamous cell carcinoma of the cervix, confined to the cervix, with no nodes on PET. She wants surgery.",
    "steps": [
      mcq("Stage",
        "What is her FIGO 2018 stage before surgery?",
        ["IB1", "IB2", "IB3", "IIB"],
        1,
        "Confined to the cervix: IB1 is 2 cm or less, IB2 over 2 and up to 4 cm, IB3 over 4 cm. Parametrial invasion would be IIB."),
      mcq("Trial",
        "Her surgeon plans a radical hysterectomy. Which trial showed that the minimally invasive (laparoscopic/robotic) approach had worse disease-free and overall survival than open surgery?",
        ["LACC", "SHAPE", "GOG 92", "KEYNOTE-A18"],
        0,
        "After LACC, radical hysterectomy for cervical cancer is done open. SHAPE showed low-risk tumors (2 cm or less, shallow) do fine with a simple hysterectomy.",
        tag=TRIAL),
      mcq("Pathology",
        "Which criteria does her pathology meet?",
        ["None; observe", "Sedlis (intermediate risk)", "Peters (high risk)", "Both"],
        1,
        "LVSI-positive with middle-third invasion and a tumor 2 cm or larger meets Sedlis. Peters features (positive nodes, positive margins, parametrial invasion) are absent.",
        context="<p><strong>Open radical hysterectomy and sentinel nodes:</strong> 3.2 cm squamous cell carcinoma, <strong>LVSI present</strong>, invasion into the <strong>middle third</strong> of the cervical stroma. Margins, parametria, and 0 of 14 nodes negative.</p>"),
      mcq("Adjuvant",
        "What adjuvant therapy do you recommend?",
        ["Observation", "Pelvic RT (IMRT), about 45-50.4 Gy", "Pelvic chemoRT with cisplatin", "Vaginal brachytherapy alone"],
        1,
        "Sedlis criteria lead to pelvic RT: GOG 92 cut recurrence roughly in half. Chemo is added for Peters features (GOG 109)."),
      fill("Target",
        "What does the target include, and how do you account for motion at simulation?",
        "The vaginal cuff and upper vagina, parametria, and pelvic nodes (common, external, and internal iliac, obturator, and presacral). Simulate with a full and an empty bladder to capture how much the cuff moves (an ITV).",
        "",
        image="images/gyn/gyn-ct-sim.jpg",
        caption="Axial planning CT for cervical cancer IMRT: primary CTV (yellow), nodal CTV (red), and an involved node (pink). Cancers (Basel) 2026 (PMC13465101), CC BY 4.0."),
      fill("Side effects",
        "What side effects of pelvic RT do you counsel her about?",
        "Acute: diarrhea and cramping, urinary frequency and burning, fatigue, and mild skin irritation. Late: vaginal dryness and stenosis (dilators), leg lymphedema (higher after node dissection plus RT), bowel or bladder injury, insufficiency fractures of the pelvis, and early menopause if the ovaries are in the field.",
        "For a young patient who still has her ovaries, ovarian transposition at surgery can move them out of the field."),
    ],
  },
  {
    "id": "gyn-case-2", "level": "Intermediate",
    "title": "Case 3: Bleeding After Intercourse",
    "oneLiner": "A 52-year-old woman who hasn't had a Pap smear in 15 years has bleeding after intercourse. Speculum exam shows a friable mass on the cervix, and the rectovaginal exam suggests thickening on the right.",
    "steps": [
      mcq("Imaging",
        "Biopsy shows squamous cell carcinoma. Which imaging best defines the parametria?",
        ["CT", "Pelvic MRI", "Ultrasound", "Bone scan"],
        1,
        "MRI shows the cervical stromal ring and whether tumor breaks through it into the parametrial fat. PET/CT then checks nodes and distant disease. FIGO 2018 lets imaging and pathology modify the stage.",
        image="images/gyn/gyn-c-cervix-exam.jpg",
        caption="Speculum view of a stage IIB cervical cancer before treatment. Moon H, Korean J Women Health Nurs 2023 (PMC10788390), CC BY 4.0."),
      fill("Stage",
        "What is her FIGO 2018 stage?",
        "IIB",
        "Parametrial invasion not reaching the pelvic side wall is IIB. Side wall involvement or hydronephrosis would be IIIB; pelvic nodes IIIC1; bladder or rectal mucosa IVA.",
        context="<p><strong>MRI:</strong> 5.2 cm cervical tumor that breaks through the right stromal ring into the parametrial fat; it does not reach the side wall; no hydronephrosis. <strong>PET/CT:</strong> no nodal or distant disease.</p>"),
      mcq("Treatment",
        "What is the standard treatment?",
        ["Radical hysterectomy", "Definitive chemoradiation with weekly cisplatin, plus brachytherapy", "Chemotherapy alone", "Pelvic RT without chemo or brachy"],
        1,
        "Locally advanced cervical cancer gets definitive chemoRT plus brachytherapy, not surgery. Adding a radical hysterectomy would stack the toxicity of both treatments without a clear gain in cure."),
      mcq("Trial",
        "Which set of trials established concurrent cisplatin with radiation as the standard for locally advanced cervical cancer?",
        ["The 1999 cisplatin trials (GOG 85, 120, 123, RTOG 9001, SWOG 8797)", "PORTEC-1 and -2", "GOG 37 and GOG 205", "LACC and SHAPE"],
        0,
        "Five trials published around 1999 showed about a 30-50% lower risk of death with concurrent cisplatin. Weekly cisplatin 40 mg/m2 is standard.",
        tag=TRIAL),
      mcq("Brachytherapy",
        "Her colleague suggests replacing brachytherapy with an IMRT or SBRT boost to save time. Is that acceptable?",
        ["Yes, they are equivalent", "No: brachytherapy puts a very high dose into the cervix with rapid falloff to the bladder and rectum, and external beam is not an equivalent substitute", "Only if she is over 70", "Only for squamous cell cancers"],
        1,
        "Leaving out brachytherapy is linked to worse survival. EMBRACE-I showed about 92% local control with MRI-guided brachytherapy, and HR-CTV D90 of 85 Gy or more predicted control.",
        image="images/gyn/gyn-c-igabt.jpg",
        caption="CT-based brachytherapy planning with a tandem-and-ovoid applicator: axial (left) and sagittal (right) views with the target and dose lines. Chen YC, Yeh CY, Cancers (Basel) 2026 (PMC12939052), CC BY 4.0."),
      fill("Prescription",
        "Give the EBRT, chemo, and brachytherapy prescription, and the time limit.",
        "Pelvic IMRT 45 Gy in 25 fractions with weekly cisplatin 40 mg/m2; HDR brachytherapy, for example 7 Gy x 4 (or 6 Gy x 5), aiming for HR-CTV D90 of 85 Gy EQD2 or more; finish everything within 56 days.",
        "Each extra day beyond 8 weeks costs roughly 0.5-1% local control.",
        image="images/gyn/gyn-c-tandem.jpg",
        caption="AP planning X-ray of a tandem-and-ovoid applicator (left) and its typical dose distribution (right). Moon H, Korean J Women Health Nurs 2023 (PMC10788390), CC BY 4.0."),
      mcq("Response",
        "Five months after treatment her cervix looks like the right-hand photo. What follow-up imaging is standard about 3 months after chemoRT?",
        ["None", "PET/CT", "Bone scan", "Mammogram"],
        1,
        "A PET/CT about 3 months after chemoRT shows whether the response is complete. A complete metabolic response is a strong sign of good outcome.",
        image="images/gyn/gyn-c-cervix-response.jpg",
        caption="The same stage IIB cervix before (A) and 5 months after (B) 50.4 Gy EBRT plus HDR brachytherapy. Moon H, Korean J Women Health Nurs 2023 (PMC10788390), CC BY 4.0."),
      mcq("What if",
        "Change one detail: MRI shows tumor invading the bladder mucosa. What is the stage, and does the plan change?",
        ["IIIB; surgery instead", "IVA; still definitive chemoRT plus brachytherapy", "IVB; palliative care only", "IIA; no change in stage"],
        1,
        "Bladder or rectal mucosal invasion is IVA, still treated for cure with chemoRT and brachytherapy. Watch for fistula.",
        image="images/gyn/gyn-mri-cx-sag.jpg",
        caption="Sagittal T2 MRI, anterior on the left: a bulky cervical cancer invading the posterior bladder wall (FIGO IVA). Otero-García et al., Insights Imaging 2019 (PMC6375059), CC BY 4.0."),
    ],
  },
  {
    "id": "gyn-case-3", "level": "Intermediate",
    "title": "Case 4: A Node on PET",
    "oneLiner": "A 45-year-old with a 3.5 cm cervical adenocarcinoma confined to the cervix on MRI has a PET/CT showing an avid 1.6 cm left external iliac node.",
    "steps": [
      mcq("Stage",
        "What is her FIGO 2018 stage?",
        ["IB2", "IIB", "IIIC1r", "IVB"],
        2,
        "Any pelvic node makes it IIIC1, whatever the size of the primary. The 'r' means radiology found it; 'p' means pathology. Para-aortic nodes would be IIIC2."),
      mcq("Surgery?",
        "Is radical hysterectomy still a good option?",
        ["Yes, with a node dissection", "No: known node-positive disease is treated with definitive chemoRT", "Only if she wants fertility preserved", "Only after induction chemo"],
        1,
        "Node-positive patients would need adjuvant chemoRT after surgery anyway (Peters), so they go straight to definitive chemoRT. If nodes are found during surgery, the hysterectomy is often abandoned in favor of chemoRT."),
      fill("Plan",
        "What is the treatment plan?",
        "Definitive pelvic chemoRT with weekly cisplatin, a boost to the involved node, and brachytherapy.",
        "Many add the para-aortic nodes when common iliac or multiple pelvic nodes are involved."),
      mcq("Trial",
        "Which trial showed better progression-free and overall survival from adding pembrolizumab during and after chemoRT for high-risk locally advanced cervical cancer?",
        ["KEYNOTE-A18", "KEYNOTE-826", "INTERLACE", "RUBY"],
        0,
        "KEYNOTE-A18 covered node-positive or stage III-IVA disease. INTERLACE added induction carboplatin and paclitaxel; KEYNOTE-826 is for metastatic or recurrent disease.",
        tag=TRIAL),
      fill("Node boost",
        "What dose does the involved node get, and when would you add the para-aortic nodes?",
        "About 55-60 Gy, usually as a simultaneous integrated boost, with the pelvis at 45 Gy in 25. Add para-aortic coverage for common iliac, multiple pelvic, or para-aortic nodes.",
        "",
        image="images/gyn/gyn-ct-sim.jpg",
        caption="Planning CT: primary CTV (yellow), elective nodal CTV (red), and the involved node (pink) that gets a boost. Cancers (Basel) 2026 (PMC13465101), CC BY 4.0."),
      mcq("Late effect",
        "She is 45 and still menstruating. Which effect of pelvic chemoRT should she expect, and plan for?",
        ["No change in her periods", "Permanent menopause from ovarian failure, with hot flashes and bone health to manage", "Temporary hair loss only", "Hearing loss from the radiation"],
        1,
        "The ovaries receive a sterilizing dose in pelvic chemoRT. In patients treated with surgery, ovarian transposition can preserve function; here it is too late, so plan for menopausal symptoms and bone health."),
    ],
  },
  {
    "id": "gyn-case-6", "level": "Intermediate",
    "title": "Case 5: One Sentinel Node",
    "oneLiner": "A 61-year-old woman has grade 3 endometrioid endometrial cancer. At surgery, one of three sentinel nodes (left external iliac) has a 6 mm metastasis.",
    "steps": [
      fill("Stage",
        "What is her FIGO stage?",
        "IIIC1 (IIIC1ii in FIGO 2023, because it is a macrometastasis)",
        "Pelvic node involvement is IIIC1; para-aortic nodes would be IIIC2. FIGO 2023 splits nodal disease into micrometastases (i) and macrometastases (ii).",
        context="<p><strong>Pathology:</strong> grade 3, 70% myometrial invasion, substantial LVSI, 1 positive pelvic sentinel node. <strong>Molecular:</strong> p53 wild-type, <strong>MMR-deficient</strong>. <strong>CT chest, abdomen, pelvis:</strong> no para-aortic or distant disease.</p>"),
      mcq("MMR",
        "What does the MMR-deficient result mean for her and her family?",
        ["Nothing", "Screen for Lynch syndrome with germline testing; MMR-deficient tumors also respond well to immunotherapy", "She needs a mastectomy", "She should avoid radiation"],
        1,
        "Lynch syndrome raises the risk of colorectal, endometrial, and other cancers in her relatives. MMR deficiency predicts benefit from checkpoint inhibitors."),
      mcq("Adjuvant",
        "Which adjuvant plan fits best?",
        ["Vaginal brachytherapy alone", "Chemotherapy ± pelvic EBRT (± immunotherapy)", "Observation", "Whole-abdomen RT"],
        1,
        "Node-positive endometrial cancer is chemo-led, with pelvic EBRT often added for pelvic and vaginal control."),
      mcq("Trial",
        "Which trial showed that chemoRT beat RT alone for survival in high-risk endometrial cancer, mainly in stage III and serous tumors?",
        ["PORTEC-3", "PORTEC-2", "GOG 258", "GOG 92"],
        0,
        "PORTEC-3 favored chemoRT over RT alone. GOG 258 found chemo alone and chemoRT had similar relapse-free survival, but RT reduced vaginal and pelvic/para-aortic recurrences, which is why many combine them.",
        tag=TRIAL),
      mcq("Immunotherapy",
        "Which systemic addition is especially helpful for her MMR-deficient tumor?",
        ["Trastuzumab", "A checkpoint inhibitor (dostarlimab or pembrolizumab) added to chemo", "Tamoxifen", "Bevacizumab"],
        1,
        "RUBY (dostarlimab) and NRG-GY018 (pembrolizumab) showed the biggest benefit in MMR-deficient advanced endometrial cancer."),
      fill("Dose",
        "If pelvic EBRT is given, what dose and target?",
        "45-50.4 Gy in 25-28 fractions to the vaginal cuff and pelvic nodes (IMRT), ± a vaginal brachytherapy boost.",
        "IIIC2 disease would extend the field up the para-aortic chain.",
        image="images/gyn/gyn-nodes-map.jpg",
        caption="Pelvic, para-aortic, and groin nodes around the uterus. The endometrium drains to the pelvic nodes and also directly from the fundus to the para-aortics. Cancer Research UK, Wikimedia Commons, CC BY-SA 4.0; labels removed."),
    ],
  },
  {
    "id": "gyn-case-4", "level": "Advanced",
    "title": "Case 6: The Node at L3",
    "oneLiner": "A 58-year-old with a 6 cm cervical squamous cell carcinoma and invasion of both parametria has PET-avid pelvic nodes and two para-aortic nodes at L3. Her kidneys are normal.",
    "steps": [
      mcq("Stage",
        "What is her FIGO 2018 stage?",
        ["IIB", "IIIC1r", "IIIC2r", "IVB"],
        2,
        "Para-aortic nodes are IIIC2, still regional and treated for cure. Supraclavicular nodes or organ metastases would be IVB.",
        image="images/gyn/gyn-g-pet-paraaortic.jpg",
        caption="An FDG-avid para-aortic node on fused PET/CT. J Imaging 2025 (PMC11856187), CC BY 4.0."),
      fill("Field",
        "Where should the top of the radiation field be?",
        "At about the renal vessels (T12-L1), above the highest involved para-aortic node.",
        "This is extended-field RT, covering the pelvis and the para-aortic chain."),
      mcq("Plan",
        "Which plan fits?",
        ["Pelvic RT only", "Extended-field chemoRT with boosts to the involved nodes, plus brachytherapy (± pembrolizumab)", "Chemo alone", "Radical hysterectomy with para-aortic dissection"],
        1,
        "IIIC2 disease gets extended-field chemoRT with nodal boosts and brachytherapy; KEYNOTE-A18 supports adding pembrolizumab for this high-risk group."),
      fill("Organs at risk",
        "Which organs at risk become important with an extended field?",
        "Kidneys (mean under about 15-18 Gy), small bowel and duodenum, spinal cord, and bone marrow.",
        ""),
      mcq("Toxicity",
        "Halfway through, her counts drop and cisplatin has to be held. Which planning goal tries to prevent this?",
        ["Femoral head V30", "Bone marrow sparing (pelvic bone V10 and V20 limits)", "Bowel bag V45", "Kidney mean dose"],
        1,
        "The pelvic bones and lumbar spine hold much of the adult marrow. Sparing it with IMRT reduces low counts and chemo interruptions."),
      mcq("Timing",
        "Because of the delays, she finishes brachytherapy on day 63. Why does that matter?",
        ["It doesn't", "Treatment longer than 56 days lowers local control by roughly 0.5-1% per extra day", "It only affects side effects", "It means she needs surgery"],
        1,
        "Tumor repopulation during prolonged treatment costs local control, which is why breaks are avoided and brachytherapy is scheduled tightly."),
    ],
  },
  {
    "id": "gyn-case-7", "level": "Advanced",
    "title": "Case 7: An Itch That Became a Sore",
    "oneLiner": "A 72-year-old woman with years of vulvar itching from lichen sclerosus has a 3.5 cm sore on the right labium. Biopsy shows squamous cell carcinoma, 5 mm deep, 3 cm from the midline. Her groins feel normal.",
    "steps": [
      mcq("Groins",
        "How should her groins be evaluated?",
        ["No groin evaluation needed", "Right sentinel node biopsy", "Bilateral full groin dissection", "Groin RT without surgery"],
        1,
        "Unifocal tumors under 4 cm with clinically negative groins get sentinel node biopsy (GROINSS-V). A lateral tumor needs only the same side; midline tumors (within 2 cm) need both sides. Only IA tumors (1 mm deep or less) skip groin evaluation."),
      fill("Stage",
        "What is her FIGO 2021 stage?",
        "IIIC (regional node with extracapsular spread)",
        "In FIGO 2021, nodes with extracapsular spread are IIIC. Fixed or ulcerated groin nodes are IVA.",
        context="<p><strong>Radical local excision:</strong> 3.5 cm SCC, closest margin 9 mm. <strong>Right sentinel node:</strong> positive, 8 mm metastasis with <strong>extracapsular extension</strong>. Completion dissection: 1 more positive node (2 of 9).</p>"),
      mcq("Adjuvant",
        "What adjuvant therapy does she need?",
        ["Observation", "RT to the groins and pelvis ± weekly cisplatin", "Vulvar RT only", "Chemo alone"],
        1,
        "Two or more positive nodes, extracapsular extension, or a sentinel node metastasis over 2 mm call for groin and pelvic RT. A sentinel micrometastasis (2 mm or less) needs groin RT alone (GROINSS-V II)."),
      mcq("Trial",
        "Which trial showed that groin and pelvic RT beat pelvic node dissection for survival in node-positive vulvar cancer?",
        ["GOG 37", "GOG 205", "GOG 92", "PORTEC-1"],
        0,
        "GOG 37 established adjuvant groin and pelvic RT. GOG 205 is the definitive chemoRT trial for locally advanced disease.",
        tag=TRIAL),
      fill("Doses",
        "Give doses for the groins and pelvis, and for the area with extracapsular extension.",
        "Groins and pelvis 45-50.4 Gy; boost the groin with ECE to about 54-64 Gy.",
        "",
        image="images/gyn/gyn-ct-groin.jpg",
        caption="Axial CT at the femoral heads with inguinal node CTVs (purple). Cancers (Basel) 2023 (PMC10741760), CC BY 4.0."),
      mcq("Late effects",
        "Which late effects are most specific to treating her groins after a dissection?",
        ["Leg lymphedema and femoral neck fracture", "Hearing loss", "Pneumonitis", "Dry mouth"],
        0,
        "Dissection plus groin RT raises lymphedema risk, and the femoral necks sit right next to the inguinal targets (keep femoral head doses low)."),
    ],
  },
  {
    "id": "gyn-case-8", "level": "Advanced",
    "title": "Case 8: A Surgery Too Big",
    "oneLiner": "A 68-year-old woman has a 7 cm vulvar squamous cell carcinoma involving the clitoris, distal urethra, and anterior vaginal wall, with a fixed 3 cm left groin node.",
    "steps": [
      mcq("Surgery?",
        "Why not proceed with surgery first?",
        ["The tumor is too small", "Clear margins would require removing the urethra (or an exenteration), with major functional loss", "Vulvar cancer never responds to surgery", "She is too young"],
        1,
        "When surgery would sacrifice the urethra, anus, or clitoris or require exenteration, definitive chemoRT is used instead, with surgery saved for residual disease.",
        image="images/gyn/gyn-c-vulva.jpg",
        caption="A large ulcerated vulvar squamous cell carcinoma (another patient). Muraoka J et al., Cureus 2024 (PMC11179657), CC BY 4.0."),
      fill("Stage",
        "What FIGO 2021 stage does the fixed groin node indicate?",
        "IVA",
        "Fixed or ulcerated groin nodes are IVA; upper urethral or bladder/rectal mucosa invasion is also IVA. Pelvic nodes or distant spread would be IVB.",
        context="<p><strong>MRI:</strong> 7 cm midline tumor involving the clitoris, distal urethra, and anterior vaginal wall. <strong>PET/CT:</strong> avid fixed 3 cm left groin node and a right groin node; no pelvic or distant nodes.</p>"),
      fill("Plan",
        "What is the treatment plan?",
        "Definitive chemoRT to the vulva, both groins, and the pelvic nodes with weekly cisplatin; biopsy any residual disease afterward and resect it if feasible.",
        ""),
      mcq("Trial",
        "Which trial established definitive chemoradiation with weekly cisplatin for locally advanced vulvar cancer, with high complete response rates?",
        ["GOG 205", "GOG 37", "KEYNOTE-A18", "PORTEC-3"],
        0,
        "GOG 205 gave 57.6 Gy with weekly cisplatin, and most complete clinical responses were confirmed pathologically, sparing many patients an exenteration.",
        tag=TRIAL),
      fill("Doses",
        "Give doses for the primary, the gross nodes, and the elective nodes, and two setup details.",
        "Primary about 57.6-64 Gy; gross nodes about 60-70 Gy; elective nodes about 45-50 Gy. Treat in a frog-leg position to reduce skin folds, with bolus on the vulva.",
        ""),
      mcq("Side effects",
        "What acute side effect will be the hardest part of her treatment?",
        ["Hair loss on the scalp", "A severe but temporary skin reaction of the vulva and groins (moist desquamation)", "Pneumonitis", "Hearing loss"],
        1,
        "Vulvar skin breaks down during treatment. Sitz baths, barrier creams, pain control, and keeping the area clean and dry help; it heals within weeks after RT. Later effects include fibrosis, stenosis, and lymphedema."),
    ],
  },
]

INTRO = "<p>Eight cases that get harder as you go, across the endometrium, cervix, and vulva. Each starts with a one-liner, then gives you more information step by step: the <strong>exam, MRI, PET, and pathology</strong>, the <strong>FIGO stage</strong>, the <strong>surgery or chemoradiation decision</strong>, the <strong>brachytherapy, doses, and targets</strong>, the <strong>landmark trials</strong>, and the <strong>side effects</strong> to counsel on. Some steps are multiple choice, some are fill-in-the-blank. Cervix uses <strong>FIGO 2018</strong>, endometrium <strong>FIGO 2023</strong> (built on the 2009 anatomic stages, with molecular classification), and vulva <strong>FIGO 2021</strong>.</p>"

if __name__ == "__main__":
    write("gyn", INTRO, CASES)
